export const EN_US = {
    AAS_BASIC_1: `Basic 1`,
    AAS_BASIC_2: `Basic 2`,
    AAS_DEVELOPER: `Developer`,
    AAS_EMAIL: `Azure Email:`,
    AAS_PASSWORD: `Azure Password:`,
    AAS_SERVER: `AAS Server:`,
    AAS_SKU: `AAS SKU:`,
    AAS_STANDARD_0: `Standard 0`,
    AAS_STANDARD_1: `Standard 1`,
    AAS_STANDARD_2: `Standard 2`,
    AAS_TITLE: `Connect to Azure Analysis Services`,
    ADF_EMAILS: `Enter one or more email addresses that will be notified when the data movement process fails.`,
    ADF_EMAILS_TITLE: `Multiple email adresses need to be comma separated.`,
    API_MANAGEMENT_SERVICE: `API Management Service:`,
    API_MANAGEMENT_TITLE: `Connect to API Management`,
    APP_CONTACT_US: `CONTACT US`,
    APP_CONTACT_US_LINK: `mailto:PBISolnTemplates@microsoft.com`,
    APP_EXPERIENCING_AN_ERROR: `Experiencing an error? Click here to let us know.`,
    APP_MICROSOFT: `Microsoft`,
    APP_POWER_BI: `Power BI`,
    APP_PRIVACY_COOKIES: `PRIVACY & COOKIES`,
    APP_PRIVACY_COOKIES_LINK: `https://www.microsoft.com/en-us/privacystatement/OnlineServices/Default.aspx`,
    APP_TERMS_USE: `TERMS OF USE`,
    APP_TERMS_USE_LINK: `https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx`,
    APP_TRADEMARKS: `TRADEMARKS`,
    APP_TRADEMARKS_LINK: `https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/en-us.aspx`,
    AZURE_ANALYSIS_LOGIN_ERROR: `An error occurred while connecting to the Azure Analysis Service.`,
    AZURE_ANALYSIS_LOGIN_SUBTITLE: `We now need to set up a connection to the Azure Analysis Services.`,
    AZURE_ANALYSIS_LOGIN_TITLE: `Connect to Azure Analysis Services`,
    AZURE_ANALYSIS_PRICING: 'Learn more about Azure Analysis Services SKUs',
    AZURE_ANALYSIS_PRICING_LINK: 'https://azure.microsoft.com/en-us/pricing/details/analysis-services/',
    AZURE_ANALYSIS_PROVISIONING: `Would you like us to provision a new Azure AS instance or use an existing instance?`,
    AZURE_LOGIN_BING_TEXT: `You can read the Bing Terms of Use`,
    AZURE_LOGIN_COGNITIVE_TEXT: `You can read the Congitive Services Terms of Use`,
    AZURE_LOGIN_CONNECT: `Connect to Azure`,
    AZURE_LOGIN_CONNECTION: `How are you signing in to your Azure subscription?`,
    AZURE_LOGIN_DIRECTORY: `Azure Tenant:`,
    AZURE_LOGIN_DIRECTORY_ADDRESS: `directoryname.onmicrosoft.com`,
    AZURE_LOGIN_DIRECTORY_DESCRIPTION: `guide`,
    AZURE_LOGIN_DIRECTORY_LINK: `http://community.powerbi.com/t5/Power-BI-Solution-Templates/Guide-for-using-Microsoft-accounts-with-Twitter-template/m-p/60088#M31`,
    AZURE_LOGIN_DIRECTORY_TEXT: `Enter the name of the Azure tenant you want to connect to. It usually looks like contoso.com or contoso.onmicrosoft.com. Not sure? Take a look at this `,
    AZURE_LOGIN_DONT_HAVE: `I don't have an Azure subscription`,
    AZURE_LOGIN_GET_STARTED: `Get started with a free`,
    AZURE_LOGIN_HAVE: `I have an Azure subscription`,
    AZURE_LOGIN_LINK: `https://azure.microsoft.com/en-us/free/`,
    AZURE_LOGIN_LINK_DESCRIPTION: `Azure subscription trial`,
    AZURE_LOGIN_MICROSOFT: `Personal Microsoft account (created by you)`,
    AZURE_LOGIN_ORGANIZATIONAL: `Work or school account (created by your IT department)`,
    AZURE_LOGIN_PRICING_TEXT: `View current Azure pricing`,
    AZURE_LOGIN_PRICING_CALCULATOR_TEXT: `You can learn more about the specific Azure resources created by this template and how to calculate estimated costs`,
    AZURE_LOGIN_RESOURCE_GROUP: `Azure Resource Group Name:`,
    AZURE_LOGIN_SUBSCRIPTION: `Azure Subscription:`,
    AZURE_LOGIN_SUBSCRIPTION_ERROR: `You do not have any Azure subscriptions linked to your account. You can get started with a free trial by clicking the link at the top of the page.`,
    AZURE_LOGIN_SUBSCRIPTION_ERROR_CRM: `You do not have any Azure subscriptions linked to your CRM account and tenant.`,
    AZURE_LOGIN_SUBTITLE: `To create the solution we will be using a number of Azure Services which require an Azure subscription.`,
    AZURE_LOGIN_UNKNOWN_ERROR: `You do not have any Azure subscriptions linked to your account. You can get started with a free trial by clicking the link at the top of the page.`,
    AX_COLLECTIONS_TEMPLATE_TITLE: `Dynamics 365 for Finance and Operations - Credit and Collections`,
    AX_CUSTOM_URL: `If you can't find your Dynamics 365 for Finance and Operations instance in the dropdown, please enter it below:`,
    AX_CUSTOM_URL_NO_DROPDOWN: `Enter your Dynamics 365 for Finance and Operations url below:`,
    AX_LOGIN_CONFIRM: `Confirm connection`,
    AX_LOGIN_CONNECT: `Connect to Dynamics 365`,
    AX_LOGIN_SUBTITLE: `To create the solution we require a connection to your Dynamics 365 for Finance and Operations instance.`,
    AX_INSTANCES: `Select your Dynamics 365 for Finance and Operations instance:`,
    AX_TITLE: `Confirm connection to Dynamics 365 for Finance and Operations`,
    AX_SUBTITLE: `Confirm the connection to Dynamics 365 for Finance and Operations so we can start pulling data.`,
    AX_UPDATE_CONFIGURATION: `Updating entities`,
    BYOE_CUSTOMIZE_ADD_ENTITY: `Add Entity`,
    BYOE_CUSTOMIZE_CSV_INVALID: `The uploaded .csv file is in an invalid state`,
    BYOE_CUSTOMIZE_EDIT_NAME: `Edit Name:`,
    BYOE_CUSTOMIZE_ENTITY_SELECT: `Select Entity:`,
    BYOE_CUSTOMIZE_ENTITY_VALUES: `Entity Values:`,
    BYOE_CUSTOMIZE_PREVIEW_OUTPUT: `Preview Output:`,
    BYOE_CUSTOMIZE_REMOVE_ENTITY: `Remove Entity`,
    BYOE_CUSTOMIZE_SELECT_ENTITY: `Get started by adding a new entity or uploading a .csv file containing your entities:`,
    BYOE_CUSTOMIZE_TITLE: `Customize Entities`,
    BYOE_CUSTOMIZE_UNIQUE_ENTITIES: `All entities must have a unique name`,
    BYOE_CUSTOMIZE_UPLOAD_ENTITIES: `Upload Entities`,
    BYOE_OPTION: `Bring your own entities? (Optional)`,
    BYOE_SUBTITLE: `Entities are collections of related words organized into categories. The template checks whether an entity is mentioned inside each article. You can then click on an entity in the report to cross filter the data. As part of the setup, you can define your own entities which will show up in the report. By default, we start you out with the following entities: Organizations, Locations, and People. As an example, if you are creating a movie themed report you could add Actors and Composers to the default list:`,
    BYOE_TITLE: `Bring Your Own Entities`,
    CHOOSE_SSAS_AZURE_ANALYSIS_SERVICES: `Yes`,
    CHOOSE_SSAS_DATA_STORAGE_MODE: `Use Azure Analysis Services (Optional):`,
    CHOOSE_SSAS_DESCRIPTION: `Azure Analysis Services is recommended for enterprise deployments supporting data volumes beyond the Power BI 1GB compressed data limit, improved performance, and almost real-time (data is refreshed every 15 minutes!).`,
    CHOOSE_SSAS_DESCRIPTION2: `Importing data into Power BI is recommended for small to medium sized installations.`,
    CHOOSE_SSAS_IMPORT_TO_PBI: `No`,
    CHOOSE_SSAS_LEARN_MORE: `The price for the Basic Tier of Azure Analysis Services is $160/month. You also have the option of choosing an existing instance of Azure Analysis Services or a more advanced tier. Learn more about Azure Analysis Services`,
    CHOOSE_SSAS_LEARN_MORE_LINK: `https://azure.microsoft.com/en-us/services/analysis-services/`,
    COGNITIVE_SERVICES_CONFIRMATION: `Enable deployment of Cognitive Services on this Azure subscription`,
    COGNITIVE_SERVICES_PRIVACY_1_A: `Your use of the Microsoft Cognitive Services is governed by your existing Azure customer agreement, which incorporates the`,
    COGNITIVE_SERVICES_PRIVACY_1_B: `including the Microsoft Cognitive Services section. You must comply with those terms, including the use and display requirements for the Bing Search APIs available at`,
    COGNITIVE_SERVICES_PRIVACY_1_C: `For example, results you obtain through the Bing Search APIs must only be used in Internet search experiences (as defined in the use and display requirements).  You are responsible for ensuring that your use of data received from the Bing Search APIs does not violate any applicable laws or third party rights.`,
    COGNITIVE_SERVICES_PRIVACY_2_A: `Microsoft may use data you send to the Cognitive Services to improve Microsoft products and services. For example, we may use content that you provide to the Cognitive Services to improve our underlying algorithms and models over time. Where you send personal data to the Cognitive Services, you are responsible for obtaining sufficient consent from the data subjects. The Microsoft Privacy Statement located`,
    COGNITIVE_SERVICES_PRIVACY_2_B: `applies to your use of the Cognitive Services, except that the Microsoft Cognitive Services section in the Online Services Terms controls to the extent it conflicts with the Microsoft Privacy Statement.  The General Privacy and Security Terms in the Online Services Terms do not apply to the Cognitive Services except where indicated in the Microsoft Cognitive Services section.`,
    COGNITIVE_SERVICES_PRIVACY_GENERIC_1_A: `Your use of the Microsoft Cognitive Services is governed by your existing Azure customer agreement, which incorporates the`,
    COGNITIVE_SERVICES_PRIVACY_GENERIC_1_B: `including the Microsoft Cognitive Services section.`,
    COGNITIVE_SERVICES_PRIVACY_GENERIC_2: `Microsoft may use data you send to the Cognitive Services to improve Microsoft products and services. For example, we may use content that you provide to the Cognitive Services to improve our underlying algorithms and models over time. Where you send personal data to the Cognitive Services, you are responsible for obtaining sufficient consent from the data subjects. The Microsoft Privacy Statement located at https://go.microsoft.com/fwlink/?LinkId=521839 applies to your use of the Cognitive Services, except that the Microsoft Cognitive Services section in the Online Services Terms controls to the extent it conflicts with the Microsoft Privacy Statement.  The General Privacy and Security Terms in the Online Services Terms do not apply to the Cognitive Services except where indicated in the Microsoft Cognitive Services section.`,
    COGNITIVE_SERVICES_PRIVACY_TWITTER: `Microsoft will use data you send to the Cognitive Services to improve Microsoft products and services. Where you send personal data to the Cognitive Services, you are responsible for obtaining sufficient consent from the data subjects. The General Privacy and Security Terms in the Online Services Terms do not apply to the Cognitive Services. Please refer to the Microsoft Cognitive Services section in the Online Services Terms for details. Microsoft offers policy controls that may be used to disable new Cognitive Services deployments.`,
    COGNITIVE_SERVICES_SUBTITLE: `This solution template deploys the Text Analytics API and the Bing News Search API of Cognitive Services.  The Text Analytics API enriches data through sentiment analysis and key phrase extraction.  The Bing News Search API finds articles based on a user’s search query. Together these services provide an advanced search solution.`,
    COGNITIVE_SERVICES_SUBTITLE_TWITTER: `This solution template deploys the Text Analytics API to carry out sentiment analysis.`,
    COGNITIVE_SERVICES_SUBTITLE_TEXT_ANALYTICS: "This solution template deploys the Text Analytics API of Cognitive Services.  The Text Analytics API enriches data through sentiment analysis and key phrase extraction.",
    COGNITIVE_SERVICES_TERMS: `Online Services Terms`,
    COGNITIVE_SERVICES_TERMS_LINK: `https://www.microsoft.com/en-us/Licensing/product-licensing/products.aspx`,
    COGNITIVE_SERVICES_TERMS_LINK2: `https://aka.ms/r1j7jq`,
    COGNITIVE_SERVICES_TITLE: `Connect to Cognitive Services`,
    COMMON_ACTION_FAILED: `Action Failed`,
    COMMON_ADVANCED_OPTIONAL: `Advanced (optional)`,
    COMMON_AND: `and`,
    COMMON_BLANK: `Blank`,
    COMMON_CHECK_OUT_THE: `Check out the`,
    COMMON_COLOR: `Color:`,
    COMMON_CONNECT: `Connect`,
    COMMON_CUSTOMIZE: `Customize`,
    COMMON_DOWNLOAD: `Download`,
    COMMON_ERROR_ID: `Error ID`,
    COMMON_EVALUATION: `For evaluation purposes only. Not intended for production use.`,
    COMMON_EXISTING: `Existing`,
    COMMON_FOR_DETAILS: `for details.`,
    COMMON_FOR_MORE_DETAILS: `for more details.`,
    COMMON_HERE: `here`,
    COMMON_ICON: `Icon:`,
    COMMON_LOGIN: `Login`,
    COMMON_MONTH_0: `January`,
    COMMON_MONTH_1: `February`,
    COMMON_MONTH_2: `March`,
    COMMON_MONTH_3: `April`,
    COMMON_MONTH_4: `May`,
    COMMON_MONTH_5: `June`,
    COMMON_MONTH_6: `July`,
    COMMON_MONTH_7: `August`,
    COMMON_MONTH_8: `September`,
    COMMON_MONTH_9: `October`,
    COMMON_MONTH_10: `November`,
    COMMON_MONTH_11: `December`,
    COMMON_MS_PRIVACY_POLICY: `Microsoft's Privacy Policy`,
    COMMON_NAME: `Name:`,
    COMMON_NEW: `New`,
    COMMON_NO: `No`,
    COMMON_OFFLINE: `There is no Internet connection`,
    COMMON_OPTIONAL: `(Optional)`,
    COMMON_PASSWORD: `password`,
    COMMON_REGISTER: `Register`,
    COMMON_ROW: `Row`,
    COMMON_ROWS: `Rows`,
    COMMON_RUN: `Run`,
    COMMON_SEE: `See`,
    COMMON_SELECT: `Select`,
    COMMON_SHOW_DOWNLOAD: `Since you are copying your data into SQL Server, you will need to use our local installer to set up the template. In order to download the solution template installer, please click the Download button below.`,
    COMMON_SUBSCRIBE: `Subscribe`,
    COMMON_TERMS_OF_USE: `Terms of Use`,
    COMMON_TOKEN: `token`,
    COMMON_UNINSTALL: `Uninstall`,
    COMMON_UNKNOWN_ERROR: `Unknown Error has occurred`,
    COMMON_USERNAME: `username`,
    COMMON_VALIDATE: `Validate`,
    COMMON_YES: `Yes`,
    CUSTOMIZE_ACTUAL_REVENUE: `Where do you want to pull your actual revenue from?`,
    CUSTOMIZE_ACTUAL_REVENUE_DESCRIPTION: `By default, we use closed CRM opportunities to calculate actual revenue. If you are planning on bringing in actual sales from another source, you can choose to keep these blank.`,
    CUSTOMIZE_BASE_URL: `Base CRM URL:`,
    CUSTOMIZE_BASE_URL_DESCRIPTION: `If you would like to navigate back to your CRM directly from the Power BI report, we need your CRM domain URL (Example: https://yourorg.crm.dynamics.com)`,
    CUSTOMIZE_CLOSED_OPPORTUNITIES: `Closed opportunities`,
    CUSTOMIZE_DAILY_TRIGGER_TIME: `Daily Trigger Time:`,
    CUSTOMIZE_DATA_RETENTION_DAYS: `Data Retention Days:`,
    CUSTOMIZE_ENDPOINT_COMPLIANCE_TARGET: `Endpoint Compliance Target:`,
    CUSTOMIZE_HEALTH_EVALUATION_TARGET: `Health Evaluation Target:`,
    CUSTOMIZE_KEEP_BLANK: `Keep Blank`,
    CUSTOMIZE_REFRESH_SCHEDULE: `Refresh Schedule:`,
    CUSTOMIZE_REFRESH_SCHEDULE_DAILY: `Daily`,
    CUSTOMIZE_REFRESH_SCHEDULE_HOURLY: `Hourly`,
    CUSTOMIZE_REFRESH_SCHEDULE_NONE: `None`,
    CUSTOMIZE_SCCM_ERROR_DATA_RETENTION_DAYS: `Data Retention Days must be a number between 1 and 365.`,
    CUSTOMIZE_SCCM_ERROR_ENDPOINT_COMPLIANCE_TARGET: `Endpoint Compliance Target must be a number between 0 and 1.`,
    CUSTOMIZE_SCCM_ERROR_HEALTH_EVALUATION_TARGET: `Health Evaluation Target must be a number between 0 and 1.`,
    CUSTOMIZE_SPECIFIC: `Make the template specific for you and your team.`,
    CUSTOMIZE_START_FISCAL_YEAR: `Start of fiscal year:`,
    CUSTOMIZE_RECURRENCE_OPTIONS: `Configure how often you want to do an incremental refresh:`,
    DATA_MOVEMENT_AZURE_DATA_FACTORY: `Azure Data Factory`,
    DATA_MOVEMENT_AZURE_DATA_FACTORY_DESCRIPTION: `Azure Data Factory is a Microsoft cloud data movement service. We create everything for the initial copy of your Salesforce data into the target database. Once that data is copied, the Azure data Factory pipeline moves new and updated records only.`,
    DATA_MOVEMENT_D365: `Dynamics 365 Export Service`,
    DATA_MOVEMENT_D365_DESCRIPTION: `The Dynamics 365 Export Service replicates Dynamics 365 (online) data to a Microsoft Azure SQL Database store in a customer-owned Microsoft Azure subscription. We create everything for the initial copy of your Dynamics 365 data into the target database. Once that data is copied, the Dynamics 365 export service moves new and updated records only.`,
    DATA_MOVEMENT_D365_PASSWORD: `Dynamics 365 Password:`,
    DATA_MOVEMENT_INFORMATICA: `Informatica`,
    DATA_MOVEMENT_INFORMATICA_AGENT: `Informatica Agent:`,
    DATA_MOVEMENT_INFORMATICA_DESCRIPTION: `Informatica is a third party service that enables you to pull data from Salesforce. When we run the setup, Informatica will copy all of your Salesforce data into your database. Once all your data is copied, Informatica will only update new and changed records making future data pulls extremely fast.`,
    DATA_MOVEMENT_INFORMATICA_NEW_ACCOUNT: `Enter your Informatica credentials below. If you don’t have an Informatica account, you can create a new account `,
    DATA_MOVEMENT_INFORMATICA_ONPREMISE_AGENT: `To finish off setting up your Informatica account you will need to install an Informatica Agent. You can download the Informatica Agent installer `,
    DATA_MOVEMENT_PASSWORD: `Password:`,
    DATA_MOVEMENT_SCRIBE: `Scribe`,
    DATA_MOVEMENT_SCRIBE_AGENT: `Scribe Agent:`,
    DATA_MOVEMENT_SCRIBE_DESCRIPTION: `Scribe is a third party service that enables you to pull data from the source application. When we run the setup, Scribe will copy all of your source application data into your database. Once all your data is copied, Scribe will only update new and changed records making future data pulls extremely fast.`,
    DATA_MOVEMENT_SCRIBE_DESCRIPTION_LINK: `You will need to perform a few extra steps before you get started. Follow the guide `,
    DATA_MOVEMENT_SCRIBE_NEW_ACCOUNT: `Create a new Scribe account `,
    DATA_MOVEMENT_SCRIBE_ONPREMISE_AGENT: `To finish off setting up this Scribe organization you will need to install a Scribe Agent. You can download the Scribe Agent installer `,
    DATA_MOVEMENT_SCRIBE_ONPREMISE_AGENT_DESCRIPTION: `Once the agent is installed, click Validate. When prompted for an installation key, use the following: `,
    DATA_MOVEMENT_SCRIBE_ORGANIZATION: `Scribe Organization:`,
    DATA_MOVEMENT_SUBTITLE: `Specify how data should be pulled from Salesforce and moved to the destination.`,
    DATA_MOVEMENT_SUBTITLE_D365: `Specify how data should be pulled from Dynamics 365 and moved to the destination.`,
    DATA_MOVEMENT_TITLE: `Move Data`,
    DATA_MOVEMENT_USERNAME: `Username:`,
    DEFAULT_TENANT: `common`,
    D365_LOGIN_ORGANIZATION_NAME: `Dynamics 365 Organization Name (case sensitive):`,
    D365_LOGIN_ORGANIZATION_URL: `Dynamics 365 Organization Url:`,
    D365_LOGIN_PASSWORD: `Dynamics 365 Password:`,
    D365_LOGIN_SUBTITLE: `We now need to set up a connection Dynamics 365 so Scribe can access the data. In order to pull data, make sure you have system customizer privileges in your Dynamics 365 instance.`,
    D365_LOGIN_TITLE: `Connect to Dynamics 365`,
    D365_LOGIN_USERNAME: `Dynamics 365 Username:`,
    EVENT_HUB_SUBTITLE: ``,
    EVENT_HUB_TITLE: `Connect to your Event Hub`,
    FACEBOOK_LOGIN_APP_ID: `Facebook App Id:`,
    FACEBOOK_LOGIN_APP_SECRET: `Facebook App Secret`,
    FACEBOOK_LOGIN_DESCRIPTION_A: `In order to use this template you will need a Facebook Developer Account and Facebook Application. You can set these up with Facebook `,
    FACEBOOK_LOGIN_DESCRIPTION_B: `For a more detailed guide go `,
    FACEBOOK_LOGIN_DESCRIPTION_C: `For a step by step guide on how to install the solution template watch the video `,
    FACEBOOK_LOGIN_DESCRIPTION_D: `For a step by step guide on how to find out your Page Id go `,
    FACEBOOK_LOGIN_DESCRIPTION_E: `For a step by step guide on how to retrieve a permanent access token for your page go `,
    FACEBOOK_LOGIN_DESCRIPTION_F: `For a step by step guide on how to retrieve a page name go  `,
    FACEBOOK_LOGIN_LINK_A: `https://developers.facebook.com/docs/apps/register#developer-account`,
    FACEBOOK_LOGIN_LINK_B: `https://github.com/Microsoft/BusinessPlatformApps/blob/dev/Source/Apps/Microsoft/Released/Microsoft-FacebookTemplate/Set%20up%20a%20Facebook%20App.md`,
    FACEBOOK_LOGIN_LINK_C: `https://www.youtube.com/watch?v=AEzHk_O1RK4&feature=youtu.be`,
    FACEBOOK_LOGIN_LINK_D: `https://www.facebook.com/help/community/question/?id=378910098941520`,
    FACEBOOK_LOGIN_LINK_E: `http://www.daniloaz.com/en/how-to-get-a-permanent-token-to-access-a-facebook-page/`,
    FACEBOOK_LOGIN_LINK_F: `https://www.facebook.com/business/help/community/question/?id=10153844635278949`,
    FACEBOOK_LOGIN_SUBTITLE: `Enter in your Facebook developer credentials`,
    FACEBOOK_LOGIN_TITLE: `Facebook Login`,
    FACEBOOK_PAGES_DESCRIPTION: `Page names should not have any spaces and can be searched on Facebook.com. To follow more than one page use commas.`,
    FACEBOOK_PAGES_FOLLOW: `Facebook Pages to follow:`,
    FACEBOOK_PAGES_SUBTITLE: `Enter in the pages you wish to follow`,
    FACEBOOK_PAGES_TITLE: `Facebook Pages`,
    FACEBOOK_LOGIN_CONNECT: `Connect to Facebook`,
    FACEBOOK_LOGIN_PAGES_SUBTITLE: `To deploy the solution we require some information about the page that you would like to monitor.`,
    FACEBOOK_LOGIN_CHOICE: `Do you own the page you would like to monitor?`,
    FACEBOOK_PAGE_ID: `Insert page id:`,
    FACEBOOK_PERMANENT_ACCESS_TOKEN: `Insert permanent page token:`,
    GETTING_STARTED_COMPANY: `Company:`,
    GETTING_STARTED_EMAIL: `Email:`,
    GETTING_STARTED_EMAIL_CONFIRMATION: `Email Confirmation:`,
    GETTING_STARTED_FIRST_NAME: `First Name:`,
    GETTING_STARTED_LAST_NAME: `Last Name:`,
    GETTING_STARTED_LIST_1: `To set up this solution template you will need:`,
    GETTING_STARTED_LIST_2: `Features of this architecture:`,
    GETTING_STARTED_NEW_VERSION: `There's a new version available!`,
    GETTING_STARTED_NEW_VERSION_INFO: `Download the latest installer so you're up to date.`,
    GETTING_STARTED_REGISTRATION_ERROR: `Invalid name, company, or email`,
    GETTING_STARTED_REGISTRATION_ERROR_EMAIL: `Invalid email domain`,
    GETTING_STARTED_TITLE: `Get started with`,
    INIT_AAL_DOWNLOAD: `Now pulling historical data, do not close this page until the tables below have loaded.`,
    INIT_AAL_DOWNLOAD_2: `Meanwhile you can download your Power BI Report.`,
    INIT_AAL_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates.  The approximate base cost of the Azure resources used by this template is $3.27 a day.  These costs are estimates only and subject to change.`,
    INIT_AAL_PRICING_URL: `https://github.com/Microsoft/BusinessPlatformApps/blob/lance-stream/README.md`,
    INIT_AAL_SUBTITLE: `Welcome to the Azure Activity Log solution template.`,
    INIT_AAL_TITLE: `Azure Activity Log Analytics`,
    INIT_ACTION_BATCH_PERMISSION: `Granting permission for logging as a batch job`,
    INIT_ACTION_CHECKING_DATA: `Checking data exists in target`,
    INIT_ACTION_CLEANING_D365_ENVIRONMENT: `Cleaning Dynamics 365 Environment`,
    INIT_ACTION_CLEANING_INFORMATICA_ENVIRONMENT: `Cleaning up the Informatica environment`,
    INIT_ACTION_CLEANING_SCRIBE_ENVIRONMENT: `Cleaning up the Scribe environment`,
    INIT_ACTION_CONFIGURING_KEY_VAULT: `Configuring Azure Key Vault`,
    INIT_ACTION_CONFIGURING_STREAM_ANALYTICS_ADMIN_OUTPUT: `Configuring Stream Analytics SQL output for Administrative data`,
    INIT_ACTION_CONFIGURING_STREAM_ANALYTICS_INPUT_EVENTHUB: `Configuring Stream Analytics input as Event Hub`,
    INIT_ACTION_CONFIGURING_STREAM_ANALYTICS_JSON_HELPER: `Configuring Stream Analytics JSON helper function`,
    INIT_ACTION_CONFIGURING_STREAM_ANALYTICS_OUTPUT_SQL: `Configuring Stream Analytics output as SQL`,
    INIT_ACTION_CONFIGURING_STREAM_ANALYTICS_QUERY: `Configuring Stream Analytics query`,
    INIT_ACTION_CONFIGURING_STREAM_ANALYTICS_SH_OUTPUT: `Configuring Stream Analytics SQL output for Service Health data`,
    INIT_ACTION_COPYING_DATALOAD_SCRIPTS: `Copy dataload scripts`,
    INIT_ACTION_CREATING_APIM_LOGGER: `Creating API Management Logger`,
    INIT_ACTION_CREATING_D365_PROFILE: `Creating Dynamics 365 Profile`,
    INIT_ACTION_CREATING_DATA_CONNECTIONS: `Creating data connections`,
    INIT_ACTION_CREATING_EVENTHUB: `Creating Event Hub`,
    INIT_ACTION_CREATING_EVENT_HUB: `Creating Event Hub service`,
    INIT_ACTION_CREATING_FUNCTION: `Creating function`,
    INIT_ACTION_CREATING_INFORMATICA_CONNECTION_SALESFORCE: `Creating Salesforce connection in Informatica`,
    INIT_ACTION_CREATING_INFORMATICA_CONNECTION_SQL: `Creating SQL connection in Informatica`,
    INIT_ACTION_CREATING_INFORMATICA_TASK: `Creating Informatica task`,
    INIT_ACTION_CREATING_LOGIC_APP_CONNECTOR: `Creating Logic App connector`,
    INIT_ACTION_CREATING_MAPPINGS: `Creating mappings to historical data`,
    INIT_ACTION_CREATING_MAPPINGS_FUTURE: `Creating mappings to future data`,
    INIT_ACTION_CREATING_POWERAPP_SQL_CONNECTION: `Creating PowerApp SQL connection`,
    INIT_ACTION_CREATING_SALESFORCE_TABLES: `Creating tables in database`,
    INIT_ACTION_CREATING_SCRIBE_CONNECTION_D365: `Creating Dynamics 365 connection in Scribe`,
    INIT_ACTION_CREATING_SCRIBE_CONNECTION_SALESFORCE: `Creating Salesforce connection in Scribe`,
    INIT_ACTION_CREATING_SCRIBE_CONNECTION_SQL: `Creating SQL connection in Scribe`,
    INIT_ACTION_CREATING_SCRIBE_SOLUTION: `Creating Scribe solution`,
    INIT_ACTION_CREATING_STREAM_ANALYTICS_JOB: `Creating Stream Analytics job`,
    INIT_ACTION_DEPLOYING_AML_EXPERIMENTS: `Deploying AML Experiments`,
    INIT_ACTION_DEPLOYING_AML_SCHEDULER: `Deploying AML Scheduler Logic App`,
    INIT_ACTION_DEPLOYING_AML_WORKSPACE: `Deploying AML Workspace`,
    INIT_ACTION_DEPLOYING_APP_SETTINGS: `Deploying App Settings`,
    INIT_ACTION_DEPLOYING_AS_MODEL: `Deploying Analysis Services model`,
    INIT_ACTION_DEPLOYING_AS_SCHEDULER: `Deploying Analysis Services scheduler`,
    INIT_ACTION_DEPLOYING_AZURE_FUNCTION: `Deploying Azure Function`,
    INIT_ACTION_DEPLOYING_AZURE_ML: `Deploying Azure ML web service`,
    INIT_ACTION_DEPLOYING_COGNITIVE_SERVICE: `Deploying Cognitive Service`,
    INIT_ACTION_DEPLOYING_COGNITIVE_SERVICE_KEY: `Deploying Cognitive Service Key`,
    INIT_ACTION_DEPLOYING_CONNECTION_STRINGS: `Deploying connection strings`,
    INIT_ACTION_DEPLOYING_DATABASE_CONFIGURATION: `Deploying database configuration`,
    INIT_ACTION_DEPLOYING_EDFI_CLOUD_RESOURCES: `Deploying EdFi cloud resources`,
    INIT_ACTION_DEPLOYING_LOGIC_APP: `Deploying Logic App`,
    INIT_ACTION_DEPLOYING_LOGIC_APP_DATABASE: `Deploying Logic App database`,
    INIT_ACTION_DEPLOYING_NEWS: `Deploying News Functions`,
    INIT_ACTION_DEPLOYING_NEWS_ASSETS: `Deploy News Function Assets`,
    INIT_ACTION_DEPLOYING_NEWS_LOGIC_APP: `Deploying News Template Logic App`,
    INIT_ACTION_DEPLOYING_NEWS_LOGIC_APP_HISTORICAL: `Deploying News Template Logic App Historical`,
    INIT_ACTION_DEPLOYING_POWERAPP: `Deploying PowerApp`,
    INIT_ACTION_DEPLOYING_SQL_SCRIPTS: `Deploying database scripts`,
    INIT_ACTION_DEPLOYING_STORAGE_ACCOUNT: `Deploying Storage Account`,
    INIT_ACTION_DEPLOYING_STORAGE_ACCOUNT_CONTAINER: `Deploy Storage Account Container`,
    INIT_ACTION_DEPLOYING_STREAM_ANALYTICS: `Deploying Stream Analytics Job`,
    INIT_ACTION_DEPLOYING_TWITTER_ASSETS: `Deploying Twitter function assets`,
    INIT_ACTION_DEPLOYING_TWITTER_FUNCTION: `Deploying Twitter function`,
    INIT_ACTION_DEPLOYING_TWITTER_LOGIC_APP: `Deploying Twitter logic app`,
    INIT_ACTION_EXPORT_ACTIVITY_LOG: `Exporting Activity Log from the Azure Portal to Event Hub`,
    INIT_ACTION_FINISHING_CLEANUP: `Finishing cleanup`,
    INIT_ACTION_GET_HISTORICAL_ACTIVITY_LOG_DATA: `Pulling 90 days of Activity Log data into SQL...This may take a few minutes.`,
    INIT_ACTION_GET_INITIAL_COUNTS: `Retrieving entitities' counts`,
    INIT_ACTION_GET_EDFI_VERSION: `Retrieving latest EdFi version`,
    INIT_ACTION_GETTING_COGNITIVE_KEY: `Getting Cognitive Key`,
    INIT_ACTION_GETTING_EVENTHUB_KEYS: `Getting EventHub Keys`,
    INIT_ACTION_GETTING_STORAGE_ACCOUNT_KEY: `Getting Storage Account Key`,
    INIT_ACTION_POPULATE_NEWS_ENTITIES: `Populating news entities`,
    INIT_ACTION_PROCESS_SCRIBE_SOLUTION: `Processing Scribe solution`,
    INIT_ACTION_REMOVING_FILES: `Removing files`,
    INIT_ACTION_REMOVING_TASK: `Removing task`,
    INIT_ACTION_RETRIEVING_POWERAPP_ENVIRONMENT: `Retrieving PowerApp environment`,
    INIT_ACTION_RETRIEVING_SALESFORCE_METADATA: `Retrieving metadata from Salesforce`,
    INIT_ACTION_RUNNING_LOGIC_APP_HISTORICAL: `Running Logic App historical`,
    INIT_ACTION_RUNNING_TASK: `Running task`,
    INIT_ACTION_SCHEDULING_DATA_LOADS: `Scheduling data loads for future data`,
    INIT_ACTION_SCHEDULING_HISTORICAL: `Scheduling one time data load for historical data`,
    INIT_ACTION_SCHEDULING_TASK: `Scheduling task`,
    INIT_ACTION_SETTING_UP_AS_SCHEDULER: `Setting up scheduler`,
    INIT_ACTION_SQL_TOOLS: `Installing SQL Tools`,
    INIT_ACTION_STARTING_D365_PROFILE: `Starting Dynamics 365 Profile`,
    INIT_ACTION_STARTING_INFORMATICA_TASK: `Starting Informatica Task`,
    INIT_ACTION_UPDATING_APIM_POLICY: `Updating API Management Policy`,
    INIT_ACTION_UPDATING_COGNITIVE_SERVICE_CONNECTOR: `Updating connector`,
    INIT_ACTION_UPDATING_LOGIC_APP_CONNECTOR: `Updating Logic App connector`,
    INIT_ACTION_VALIDATING_D365_ENTITIES: `Validating Dynamics 365 Entities`,
    INIT_ACTION_VALIDATING_D365_PROFILE: `Validating Dynamics 365 Profile`,
    INIT_ACTION_VALIDATING_LOGIC_APP: `Validating Logic App`,
    INIT_ACTION_VALIDATING_NEWS: `Validating News Function`,
    INIT_ACTION_VALIDATING_STORAGE_ACCOUNT: `Validating Storage Account`,
    INIT_ACTION_VALIDATING_STORAGE_ACCOUNT_KEY: `Validating Storage Account Key`,
    INIT_ACTION_VALIDATING_TWITTER_FUNCTION: `Validating Twitter function`,
    INIT_ACTION_VERIFY_EVENT_HUB: `Verifying the insights-operational-logs Event Hub`,
    INIT_ACTION_WAITING_AS_SCHEDULER: `Waiting for Analysis Services scheduler`,
    INIT_ACTION_WAITING_DATA: `Waiting for data to appear in the destination`,
    INIT_ACTION_WAITING_DEPLOYMENT: `Waiting for deployment`,
    INIT_API_MANAGEMENT_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates.The approximate base cost of the Azure resources used by this template is $X.XX a day.These costs are estimates only and subject to change.`,
    INIT_API_MANAGEMENT_PRICING_URL: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_API_MANAGEMENT_SUBTITLE: `Welcome to the API Management solution template`,
    INIT_API_MANAGEMENT_TITLE: `API Management`,
    INIT_AZURE_PRICING_CALCULATOR_URL: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_D365_CALCULATOR: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_D365_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates. The approximate cost for the Azure SQL Database and Azure Key Vault required is $75 per month. These costs are estimates only and subject to change. The Azure premium tier Azure SQL Database is recommended during the initial data export and can be moved to a less expensive service tier after this step is completed.`,
    INIT_D365_PRICING_URL: `https://github.com/Microsoft/BusinessPlatformApps/tree/master/Source/Apps/Microsoft/Released/Microsoft-CRMSalesManagement#dynamics-365-export-pricing`,
    INIT_D365_CS_TITLE: `Dynamics 365 Customer Service for Dynamics 365 Analytics`,
    INIT_D365_FS_TITLE: `Dynamics 365 Field Service for Dynamics 365 Analytics`,
    INIT_D365_PSA_TITLE: `Dynamics 365 Project Services Automation for Dynamics 365 Analytics`,
    INIT_D365_TITLE: `Sales Management for Dynamics 365`,
    INIT_FACEBOOK_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates. The approximate base cost of the Azure resources used by this template is $300 a month, and every 1,000 posts or comments will incur an additional cost of approximately $1.50. These costs are estimates only and subject to change.`,
    INIT_FACEBOOK_PRICING_URL: `https://github.com/Microsoft/BusinessPlatformApps/blob/dev/Source/Apps/Microsoft/Released/Microsoft-FacebookTemplate/README.md`,
    INIT_GETTING_STARTED_AZURE_COGNITIVE_SERVICES: `Azure access to Cognitive Services`,
    INIT_GETTING_STARTED_AZURE_SQL: `Azure SQL Database`,
    INIT_GETTING_STARTED_AZURE_SUBSCRIPTION: `Azure Subscription`,
    INIT_GETTING_STARTED_AZURE_VM: `Azure VM/On Premises Environment`,
    INIT_GETTING_STARTED_CLOUD_SOLUTION: `Full cloud solution with minimum set up and maintenance considerations`,
    INIT_GETTING_STARTED_CONNECT_AS_PBI: `Connect to Azure SQL and import data into Power BI`,
    INIT_GETTING_STARTED_D365_ADMIN: `You must be a Dynamics 365 Administrator`,
    INIT_GETTING_STARTED_D365_AZURE_TENANT: `A valid Azure subscription in the same Azure tenant as the Dynamics 365 instance`,
    INIT_GETTING_STARTED_D365_DECEMBER: `December 2016 update for Microsoft Dynamics 365 (online) or a later instance`,
    INIT_GETTING_STARTED_D365_EXPORT: `Data pulled from Dynamics 365 into an Azure SQL Database using the Dynamics 365 Export Service`,
    INIT_GETTING_STARTED_D365_ONLINE: `Dynamics 365 Online`,
    INIT_GETTING_STARTED_D365_ONPREMISE: `Dynamics 365 On Premise`,
    INIT_GETTING_STARTED_D365_PULL: `Data pulled from Dynamics 365 into an Azure SQL Database`,
    INIT_GETTING_STARTED_D365_VOLUME: `The target Azure Database must support the volume of data being replicated from your Dynamics 365 instance`,
    INIT_GETTING_STARTED_DATA_MODEL: `Import a data model into Power BI`,
    INIT_GETTING_STARTED_DATA_MODEL_EXCEED: `Your data model doesn't exceed 1GB (about 10 million rows for opportunities, accounts, and leads)`,
    INIT_GETTING_STARTED_DATA_PULL_SALESFORCE: `Data pulled from Salesforce into an Azure SQL Database using Azure Data Factory`,
    INIT_GETTING_STARTED_DATA_PULL_SAP: `Data pulled daily from SAP & stored in a database optimized for reporting`,
    INIT_GETTING_STARTED_DATA_PULL_SCCM: `Data pulled daily from System Center Configuration Manager & stored in a SQL database optimized for reporting`,
    INIT_GETTING_STARTED_DEDICATED_SSAS: `Use an on premises SQL Server but without a dedicated Analysis Services Server`,
    INIT_GETTING_STARTED_DESTINATION: `Destination database: Azure SQL database or SQL Server database (SQL Server 2008 R2 SP3 or later).`,
    INIT_GETTING_STARTED_ENTERPRISE_GATEWAY: `Set up an Enterprise Gateway to talk to Power BI`,
    INIT_GETTING_STARTED_EXPORT_ACTIVITY_LOG: `Export Activity Log to Event Hub with Log Profiles`,
    INIT_GETTING_STARTED_FACEBOOK: `Facebook Developer Account`,
    INIT_GETTING_STARTED_IMPORT_DATA_PBI: `Import data into powerful Power BI reports`,
    INIT_GETTING_STARTED_NET: `For the machine where the installation is run, Microsoft .NET Framework 4.5 or later & PowerShell version 5.0 or later.`,
    INIT_GETTING_STARTED_O365_ADMIN_CREDENTIALS: `Office 365 Administrator Credentials`,
    INIT_GETTING_STARTED_PBI_DESKTOP: `Power BI Desktop (latest version)`,
    INIT_GETTING_STARTED_PBI_PRO: `Power BI Pro (to share the template with your organization)`,
    INIT_GETTING_STARTED_PULL_DATA: `Pull data into SQL Server (this could be on an Azure VM or on premises)`,
    INIT_GETTING_STARTED_SALESFORCE_SUBSCRIPTION: `Salesforce Subscription`,
    INIT_GETTING_STARTED_SAP_READ_ACCESS: `Read access to the SAP Database`,
    INIT_GETTING_STARTED_SCALABLE: `Scalable and extensible solution with minimum set up and maintenance considerations`,
    INIT_GETTING_STARTED_SCCM: `System Center 2012 Configuration Manager R2 SP1 or later. Read access to System Center Configuration Manager database is required.`,
    INIT_GETTING_STARTED_SIMPLEMENT_TRIAL: `A Simplement Trial Account`,
    INIT_GETTING_STARTED_SQL_ONPREMISE: `SQL Server On Premise`,
    INIT_GETTING_STARTED_SQL_SERVER: `SQL Server (2012 R2 or later)`,
    INIT_GETTING_STARTED_STREAM_ANALYTICS_EVENT_HUB: `Process Event Hub data in near real-time with Stream Analytics`,
    INIT_GETTING_STARTED_TWITTER: `Twitter Account`,
    INIT_GETTING_STARTED_TWITTER_REAL_TIME: `Real time data pulled from Twitter & enriched using machine learning`,
    INIT_GETTING_STARTED_WHAT_D365: `What Dynamics 365 instance do you use?`,
    INIT_GETTING_STARTED_WHERE: `Where do you want to copy your data?`,
    INIT_NEWS_DOWNLOAD: `Open the Power BI report (.pbix file) to explore your data. If you have opened your report but are not seeing any data, check back in a few hours. It could take some time to find articles. Publish the report for others to see in your Power BI workspace. You will need Power BI Desktop to open this file - download it`,
    INIT_NEWS_PRICING_CALCULATOR: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_NEWS_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates.  The approximate base cost of the Azure resources used by this template is $10 a day, and every 1,000 articles will incur an additional cost of approximately $12.  These costs are estimates only and subject to change.`,
    INIT_NEWS_PRICING_URL: `https://github.com/Microsoft/BusinessPlatformApps/blob/dev/Source/Apps/Microsoft/Released/Microsoft-NewsTemplate/README.md`,
    INIT_NEWS_RESULTS: `Data and search results enriched using machine learning techniques like topic modelling and entity extraction`,
    INIT_NEWS_SEARCH: `Search articles from hundreds of news publishers to find the most relevant results`,
    INIT_NEWS_SUBTITLE: `Welcome to the Bing News Advanced Search solution template.`,
    INIT_NEWS_TITLE: `Advanced Search with Bing News`,
    INIT_PBI_TELEMETRY_PRICING_CALCULATOR_URL: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_PBI_TELEMETRY_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates. The approximate base cost of the Azure resources used by this template is $X.XX a day. These costs are estimates only and subject to change.`,
    INIT_PBI_TELEMETRY_PRICING_URL: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_PBI_TELEMETRY_SUBTITLE: `Welcome to the Power BI (and O365) solution template.`,
    INIT_PBI_TELEMETRY_TEMPLATE_NAME: `Power BI (and O365) Adoption Solution Template`,
    INIT_SALESFORCE_PRICING_CALCULATOR_URL: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_SALESFORCE_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates. The approximate base cost of the Azure resources used by this template is $1.50 a day. The cost will vary with the amount of data that will be moved. These costs are estimates only and subject to change.`,
    INIT_SALESFORCE_PRICING_URL: `https://github.com/Microsoft/BusinessPlatformApps/tree/master/Source/Apps/Microsoft/Released/Microsoft-SalesforceSalesManagement#azure-data-factory-pricing`,
    INIT_SALESFORCE_SUBTITLE: `Welcome to the Salesforce Sales Management solution template.`,
    INIT_SALESFORCE_TITLE: `Salesforce Sales Management`,
    INIT_SAP_LOGIN: `Specify your windows credentials to create a recurring schedule that will pull data from SAP.`,
    INIT_SAP_SUBTITLE: `Welcome to the Accounts Receivable Reporting for SAP solution template.`,
    INIT_SAP_TITLE: `Accounts Receivable Reporting for SAP`,
    INIT_SCCM_LOGIN: `Specify your windows credentials to create a recurring schedule. The credentials you specify will also be used to connect to the SCCM database`,
    INIT_SCCM_SUBTITLE: `Welcome to the System Center Configuration Manager solution template.`,
    INIT_SCCM_TITLE: `System Center Configuration Manager`,
    INIT_SIMPLEMENT_CONTACT: ` contact Simplement.`,
    INIT_SIMPLEMENT_PRIVACY: `By using this Simplement trial account, you agree to the`,
    INIT_SIMPLEMENT_PRIVACY_TITLE: `Simplement Privacy Statement`,
    INIT_SIMPLEMENT_TRIAL: `To use this solution template you need a trial account with Simplement. Enter your information below to register with Simplement for 30 days. To extend the trial account with Simplement or arrange a proof of concept in your environment`,
    INIT_SIMPLEMENT_YES: `Yes, I want to hear from Simplement on how I can extend this trial account or new offers`,
    INIT_SOURCE_SCCM_SUBTITLE: `Set up a connection to your SCCM database so we can bring in your data.`,
    INIT_SOURCE_SCCM_TITLE: `Connect to your System Center Configuration Manager database`,
    INIT_SQL_SUBTITLE: `Set up a connection to your target database so we can transfer your data.`,
    INIT_SQL_SUBTITLE_AAL: `Set up a connection to SQL so we can bring in your Azure Activity Log data.`,
    INIT_SQL_SUBTITLE_D365: `Set up a connection to SQL so we can bring in your Dynamics 365 data.`,
    INIT_SQL_SUBTITLE_NEWS: `Set up a connection to SQL so we can bring in Bing News data.`,
    INIT_SQL_TITLE: `Connect to your SQL database`,
    INIT_TARGET_SALESFORCE: `Set up a connection to SQL so we can bring in your Salesforce data.`,
    INIT_TWITTER_PRICING_CALCULATOR_URL: `https://azure.microsoft.com/en-us/pricing/calculator/`,
    INIT_TWITTER_PRICING_COST: `By clicking next and deploying the template, you authorize Microsoft to create Azure resources on your subscription and bill based on their respective pricing rates. The approximate base cost of the Azure resources used by this template is $4.33 a day, and every 1,000 tweets will incur an additional cost of approximately $0.8. These costs are estimates only and subject to change.`,
    INIT_TWITTER_PRICING_URL: `https://github.com/Microsoft/BusinessPlatformApps/blob/dev/Source/Apps/Microsoft/Released/Microsoft-TwitterTemplate/README.md#estimated-costs`,
    INIT_TWITTER_SQL_SUBTITLE: `Set up a connection to SQL so we can bring in your Twitter data.`,
    INIT_TWITTER_SQL_TITLE: `Connect to your SQL Database`,
    INIT_TWITTER_SUBTITLE: `Welcome to the brand and campaign management solution template.`,
    INIT_TWITTER_TEMPLATE_NAME: `Brand and Campaign Management for Twitter`,
    INIT_UNINSTALL_SAP: `The task used to move data between the SAP application server and the target database`,
    INIT_UNINSTALL_SCCM: `The task used to move data between the SCCM database and the target database`,
    INIT_UNINSTALL_SQL: `The scripts used to create the initial tables in the target database`,
    INIT_UNINSTALL_SUCCESS: `Uninstall complete`,
    KEYVAULT_LOGIN_ERROR: `An error occurred while connecting to the Azure Key Vault Service.`,
    KEYVAULT_LOGIN_SUBTITLE: `We now need to set up a connection to the Azure Key Vault.`,
    KEYVAULT_LOGIN_TITLE: `Connect to Azure Key Vault`,
    MSCRM_LOGIN_CONNECT: `Connect to my Azure Subscription with Dynamics 365`,
    MSCRM_LOGIN_ERROR: `An error occurred while connecting to the Dynamics 365 Export Service.`,
    MSCRM_LOGIN_NO_AUTHORIZATION: `No Dynamics 365 organizations were found in which your account has Administrator privileges.`,
    MSCRM_LOGIN_NO_ORGANIZATIONS: `No Dynamics 365 Organizations Found.`,
    MSCRM_LOGIN_ORGANIZATION: `Dynamics 365 Organization:`,
    MSCRM_LOGIN_SUBTITLE: `We now need to set up a connection to Dynamics 365.`,
    MSCRM_LOGIN_TITLE: `Connect to Dynamics 365`,
    NAVBAR_MICROSOFT_PRIVACY_STATEMENT: `Microsoft's Privacy Statement`,
    NAVBAR_MICROSOFT_PRIVACY_STATEMENT_LINK: `https://www.microsoft.com/en-us/privacystatement/OnlineServices/Default.aspx`,
    NAVBAR_TERMS_USE: `Terms of Use`,
    NAVBAR_TERMS_USE_LINK: `https://bpsolutiontemplates.com/terms-of-use.html`,
    NAVIGATION_BACK: `Back`,
    NAVIGATION_LOGS: `Navigate here to view logs:`,
    NAVIGATION_MS_PRIVACY: `Information gathered is used by Microsoft to replicate information from the source application to the destination database. By using this solution template, you agree to Microsoft’s terms and privacy statement. Read the Microsoft privacy statement to learn more about how your information is used.`,
    NAVIGATION_MS_PRIVACY_LINK: `https://www.microsoft.com/en-us/privacystatement/OnlineServices/Default.aspx`,
    NAVIGATION_MS_PRIVACY_LINK_TEXT: `Microsoft Privacy Statement`,
    NAVIGATION_SUCCESSFULLY_VALIDATED: `Successfully validated`,
    NAVIGATION_VIEW_DETAILS: `View Details`,
    NOTIFIER_INSERTING_INITIAL_COUNTS: `Inserting initial entity counts`,
    NOTIFIER_CREATING_DATABASE_CONNECTION: `Creating database conection`,
    NOTIFIER_CREATING_NOTIFIER_APP: `Creating notifier app`,
    NOTIFIER_CONFIGURE_NOTIFIER_APP: `Configuring notifications`,
    O365_LOGIN_SUBTITLE: `Set up a connection to your Office 365 Account so we can bring in your data.`,
    O365_LOGIN_TITLE: `Connect to your Office 365 Account`,
    POWER_BI_SIGN_IN: 'Sign In',
    POWER_BI_SIGN_UP: 'Sign up free',
    POWER_BI_LEARN_MORE: 'Learn more',
    PROGRESS_ALL_DONE: `The deployment successfully completed! You can now download your Power BI report and close this page.`,
    PROGRESS_ALL_DONE2: `If you requested a notification mail, we will let you know when your data is ready.`,
    PROGRESS_DOWNLOAD_PBIX: `Download Report`,
    PROGRESS_DOWNLOAD_PBIX_INFO: 'Open the Power BI report (.pbix file) to explore your data. Publish the report for others to see in your Power BI workspace. You will need Power BI Desktop to open this file - download it ',
    PROGRESS_DOWNLOAD_POWERAPP_INFO: 'If you or someone else needs to change the twitter query later, download the Power App (or .msapp file). Use PowerApps studio to run the app or share with others. Download PowerApps Studio',
    PROGRESS_GETTING_READY: `Getting your Power BI file ready...`,
    PROGRESS_GETTING_READY_POWERAPP: `Getting your PowerApp file ready...`,
    PROGRESS_PUBLISH_PBIX: `Publish Report`,
    PROGRESS_SUBTITLE: `This might take a while. We'll show you progress while you wait. Please don't close the browser until all the steps are completed. The setup could take 10-15 minutes.`,
    PROGRESS_TITLE: `Track your progress`,
    PROGRESS_UNSUBSCRIBE: `You can unsubscribe at any time.`,
    PROGRESS_VIEW_PBIX: `View Report`,
    PROGRESS_VIEW_POWERAPP: `View PowerApp`,
    PROGRESS_WORKSPACES_DESTINATION: `Select a destination:`,
    PROGRESS_WORKSPACES_TITLE: `Publish to Power BI`,
    RECURRENT_NEVER: `Never`,
    RECURRENT_15_MINUTES: `Every 15 minutes`,
    RECURRENT_30_MINUTES: `Every 30 minutes`,
    RECURRENT_HOURLY: `Hourly`,
    RECURRENT_DAILY: `Daily`,
    SALESFORCE_LOGIN_PASSWORD: `Salesforce Password:`,
    SALESFORCE_LOGIN_SUBTITLE: `We now need to set up a connection to Salesforce in order to pull data.`,
    SALESFORCE_LOGIN_TITLE: `Login to Salesforce`,
    SALESFORCE_LOGIN_TOKEN: `Salesforce Token:`,
    SALESFORCE_LOGIN_TOKEN_DESCRIPTION: `If you do not know what your security token is, or how to get it, please contact your Salesforce administrator.`,
    SALESFORCE_LOGIN_URL: `Salesforce Online URL:`,
    SALESFORCE_LOGIN_USERNAME: `Salesforce Username:`,
    SAP_APPLICATION_SERVER: `Application Server: `,
    SAP_APPLICATION_SERVER_DESCRIPTION: `Name of the host to which you want to connect.`,
    SAP_CLIENT: `Client: `,
    SAP_CLIENT_DESCRIPTION: `Always three numeric characters.`,
    SAP_INSTANCE_NUMBER: `Instance Number: `,
    SAP_INSTANCE_NUMBER_DESCRIPTION: `Instance number of the SAP system to which you want to connect. Always two numeric digits. Formerly called System Number.`,
    SAP_LANGUAGE: `Language:`,
    SAP_PASSWORD: `Password:`,
    SAP_ROUTER_STRING: `SAP Router String:`,
    SAP_ROW_BATCH_SIZE: `Row Batch Size:`,
    SAP_SYSTEM_ID: `System ID: `,
    SAP_SYSTEM_ID_DESCRIPTION: `System ID of the SAP system to which you want to connect.`,
    SAP_SUBTITLE: `We now need to set up a connection to your SAP ECC source system.`,
    SAP_TITLE: `SAP Source System Connection Information`,
    SAP_USER: `User:`,
    SCRIBE_LOGIN_ORGANIZATION: `Scribe Organization:`,
    SCRIBE_LOGIN_PASSWORD: `Scribe Password:`,
    SCRIBE_LOGIN_SUBTITLE: `Let’s start by setting up your Scribe Account. Scribe is a third party service that enables you to pull data from Dynamics 365. When we run the setup, Scribe will copy all of your Dynamics 365 data into your database. Once all your data is copied, Scribe will only update new and changed records making future data pulls extremely fast.`,
    SCRIBE_LOGIN_TITLE: `Connect to your Scribe Account`,
    SCRIBE_LOGIN_USERNAME: `Scribe Username:`,
    SEARCH_TERMS_GUIDELINES: `Twitter search query guidelines`,
    SEARCH_TERMS_LINK: `https://dev.twitter.com/rest/public/search`,
    SEARCH_TERMS_NEWS_LINK: `https://www.microsoft.com/cognitive-services/en-us/bing-news-search-api`,
    SEARCH_TERMS_NEWS_LINK_DESCRIPTION: `Preview your news results`,
    SEARCH_TERMS_NEWS_SUBTITLE: `Input the search terms you want to track. We will use advanced techniques to search for articles relevant to your query.`,
    SEARCH_TERMS_QUERY: `Search Query:`,
    SEARCH_TERMS_QUERY_EXAMPLE: `@MSPowerBI OR Azure OR "Stream Analytics"`,
    SEARCH_TERMS_QUERY_EXAMPLE_NEWS: `Microsoft OR Azure`,
    SEARCH_TERMS_SUBTITLE: `Input the search terms you want to track. We will collect all tweets that match your search criteria. We can track hashtags, Twitter handles, plain text and more. For example, if you are interested in tweets that mention Azure or the Power BI Twitter handle, you would put: @MSPowerBI OR Azure.`,
    SEARCH_TERMS_TITLE: `Customize your search terms`,
    SQL_ERROR_PASSWORD_LENGTH: `Password must be at least eight characters long.`,
    SQL_ERROR_PASSWORD_MATCH: `Passwords do not match.`,
    SQL_ERROR_PASSWORD_SPACES: `Password should not contain spaces.`,
    SQL_ERROR_PASSWORD_SPECIAL_CHARACTERS: `Password must contain at least one uppercase character and at least one special character.`,
    SQL_ERROR_USERNAME_ALPHANUMERIC: `must only contain alphanumeric characters or hyphens.`,
    SQL_ERROR_USERNAME_HYPHEN: `must not start or end with a hyphen.`,
    SQL_ERROR_USERNAME_LENGTH: `must not be longer than 63 characters.`,
    SQL_ERROR_USERNAME_RESERVED: `cannot be a reserved SQL system name.`,
    SQL_ERROR_USERNAME_SPACES: `should not contain spaces.`,
    SQL_SERVER_AUTHENTICATION: `Authentication: `,
    SQL_SERVER_CHECK_AVAILABILITY: `Check Availability`,
    SQL_SERVER_CREATE_AZURE_SQL: `Create a new Azure SQL instance to host the source system's data`,
    SQL_SERVER_CREATING_NEW: `Creating a new SQL database, this may take 2-3 minutes`,
    SQL_SERVER_DATABASE: `Database:`,
    SQL_SERVER_DATABASE_RECOVERY: `(Simple/bulk recovery mode is recommended)`,
    SQL_SERVER_EXISTING: `Existing SQL Instance`,
    SQL_SERVER_IMPERSONATION: `This option will impersonate the previously chosen Windows user`,
    SQL_SERVER_LOCATION: `Server Location`,
    SQL_SERVER_NEW: `New Azure SQL Instance`,
    SQL_SERVER_PASSWORD: `Password: `,
    SQL_SERVER_PASSWORD_CONFIRMATION: `Password Confirmation:`,
    SQL_SERVER_PASSWORD_DESCRIPTION: `The password for the chosen windows account. This is required to pull data in an unattended mode.`,
    SQL_SERVER_PASSWORD_NEW_DESCRIPTION: `Password must be at least eight characters including one uppercase letter, one special character and one number.`,
    SQL_SERVER_PROVISION: `Would you like us to provision a new Azure SQL instance or use an existing SQL instance?`,
    SQL_SERVER_SERVER_NAME: `Server Name:`,
    SQL_SERVER_SKU: `Server Sku:`,
    SQL_SERVER_SKU_DESCRIPTION: `Performance and cost information for the different Azure SQL Database tiers are available`,
    SQL_SERVER_SKU_LINK: `https://azure.microsoft.com/en-us/pricing/details/sql-database/`,
    SQL_SERVER_SKU_P1: `P1`,
    SQL_SERVER_SKU_S1: `S1`,
    SQL_SERVER_SKU_S2: `S2`,
    SQL_SERVER_SKU_S3: `S3`,
    SQL_SERVER_STANDARD_AZURE: `We will create a Standard Azure instance inside your Azure Subscription.`,
    SQL_SERVER_USERNAME: `SQL Username:`,
    SQL_SERVER_USING_AZURE: `Using Azure SQL?`,
    SQL_SERVER_USING_GOV_AZURE: `Government Azure`,
    SQL_SERVER_WINDOWS: `Windows Username: `,
    SQL_SERVER_WINDOWS_DESCRIPTION: `Must be in <domain>\\<username> or <machinename>\\<username> format`,
    SSAS_INVALID_SERVER_NAME: `Server name must begin with a letter, be lowercase alphanumeric, and be between 3 and 63 characters in length.`,
    SSAS_SUBTITLE: `Would you like to use Azure Analysis Services?`,
    SSAS_TITLE: `Scale with Azure Analysis Services`,
    SUMMARY_EMAIL_ADDRESS: `Email Address:`,
    SUMMARY_NOTIFICATION: `Getting this set up could take a while. We can notify you when everything is ready.`,
    SUMMARY_SEND_COMPLETION_NOTIFICATION: `Yes, send me a notification.`,
    SUMMARY_SEND_MARKETING_MAIL: `Sign up to stay connected with information about new templates, enhancements, tips and tricks.`,
    SUMMARY_SUBTITLE: `Please verify that the information provided below is correct. If you are ready click Run to begin building the solution template.This will also download the pbix file which you can begin exploring as soon as the setup finishes.`,
    SUMMARY_TITLE: `Verify and run solution`,
    TWITTER_CONNECT: 'Connect to Twitter',
    TWITTER_HANDLES_OPTIONAL: `Twitter Handles (optional):`,
    TWITTER_HANDLES_SUBTITLE: `We can enrich tweets with the tweet direction. If you would like to track whether a tweet was tweeted to or from a specific account, please explicitly list the Twitter Handles you are interested in.`,
    TWITTER_HANDLES_TITLE: `Customize your twitter handles`,
    TWITTER_SUBTITLE: `Set up a connection to your Twitter account so we can pull data. You will get to customize the search queries you want to track later on in the installation.`,
    TWITTER_TITLE: `Connect to Twitter`,
    TWITTER_VALIDATED: `Validated`,
    UNINSTALL_SUBTITLE: `The uninstaller will remove:`,
    WINDOWS_AUTH_CURRENT: `Log in as current user?`,
    WINDOWS_AUTH_PASSWORD: `Password:`,
    WINDOWS_AUTH_TITLE: `Connect to Windows`,
    WINDOWS_AUTH_USERNAME: `Windows Username:`,
    WINDOWS_AUTH_USERNAME_DESCRIPTION: `Must be in <domain>\\<username> or <machinename>\\<username> format`,
    WINDOWS_AUTH_USERNAME_ERROR: `Please enter your username`,
    WINDOWS_AUTH_USERNAME_ERROR_2: `Username must be in <domain>\\<username> or <machinename>\\<username> format.`
};