SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='napbi')
BEGIN
    EXEC ('CREATE SCHEMA napbi AUTHORIZATION dbo');
END;

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='napbi' AND TABLE_NAME='O365AuditLog' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE napbi.O365AuditLog;
