SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Views
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='RequestResponse' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.RequestResponse;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='APIMErrorDetail' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.APIMErrorDetail;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='RequestResponse' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.RequestSummary;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='vw_date' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.vw_date;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='ApiSummary' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.ApiSummary;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='OperationSummary' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.OperationSummary;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='ProductSummary' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.ProductSummary;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='SubscriptionSummary' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.SubscriptionSummary;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='AllRequestData' AND TABLE_TYPE='VIEW')
    DROP VIEW dbo.AllRequestData;

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Request' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Request;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Response' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Response;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Error' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Error;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallExtendedEdgeList' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallExtendedEdgeList;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallExtendedEdgeList_STAGE' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallExtendedEdgeList_STAGE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallProbabilityEdgeList' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallProbabilityEdgeList;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallProbabilityEdgeList_STAGE' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallProbabilityEdgeList_STAGE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='FFT' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.FFT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='FFT_STAGE' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.FFT_STAGE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Date' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Date;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='GeoLite2-City-Blocks-IPv4' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.[GeoLite2-City-Blocks-IPv4];
