SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Request' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Request;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Response' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Response;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Error' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Error;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallExtendedEdgeList' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallExtendedEdgeList;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallExtendedEdgeList_STAGE' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallExtendedEdgeList_STAGE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallProbabilityEdgeList' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallProbabilityEdgeList;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='CallProbabilityEdgeList_STAGE' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.CallProbabilityEdgeList_STAGE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='FFT' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.FFT;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='FFT_STAGE' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.FFT_STAGE;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Date' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.Date;