SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='rpt_Date' AND TABLE_TYPE='VIEW')
    DROP VIEW [vs].[rpt_Date];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='rpt_Iteration' AND TABLE_TYPE='VIEW')
    DROP VIEW [vs].[rpt_Iteration];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='rpt_Person' AND TABLE_TYPE='VIEW')
    DROP VIEW [vs].[rpt_Person];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='rpt_Project' AND TABLE_TYPE='VIEW')
    DROP VIEW [vs].[rpt_Project];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='rpt_WorkItemRevision' AND TABLE_TYPE='VIEW')
    DROP VIEW [vs].[rpt_WorkItemRevision];

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='Person' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[Person];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='Project' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[Project];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='Iteration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[Iteration];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='Date' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[Date];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='WorkItemRevision' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[WorkItemRevision];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='stg_Iteration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[stg_Iteration];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='stg_Project' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[stg_Project];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='stg_WorkItem' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[stg_WorkItem];
	IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='vs' AND TABLE_NAME='configuration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE [vs].[configuration];

-- Stored Procedures
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='vs' AND ROUTINE_NAME='Merge' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE vs.[Merge];

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='vs')
BEGIN
    EXEC ('CREATE SCHEMA vs AUTHORIZATION dbo'); -- Avoid batch error
END;
