
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RedditCore.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class EmbeddedUrl
{

    public long Id { get; set; }

    public string DocumentId { get; set; }

    public string ContentEmbeddedUrl { get; set; }

    public string ContentEmbeddedUrlDomain { get; set; }

}

}
