
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RedditCore.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class UserDefinedEntity
{

    public string DocumentId { get; set; }

    public string Entity { get; set; }

    public string EntityType { get; set; }

    public Nullable<int> EntityOffset { get; set; }

    public Nullable<int> EntityLength { get; set; }

    public long Id { get; set; }

}

}
