
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RedditCore.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class UserDefinedEntityDefinition
{

    public string Regex { get; set; }

    public string EntityType { get; set; }

    public string EntityValue { get; set; }

    public string Color { get; set; }

}

}
