SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='adtlog')
BEGIN
    EXEC ('CREATE SCHEMA adtlog AUTHORIZATION dbo');
END;


    -- Regular views
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='vwaudit_data_powerbi' AND TABLE_TYPE='VIEW')
    DROP VIEW adtlog.vwaudit_data_powerbi;

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='audit_data' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.audit_data;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='batch_log' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.batch_log;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='O365AuditLog' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.O365AuditLog;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='datasets' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.datasets;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='staging_audit_data' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.staging_audit_data;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='staging_datasets' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.staging_datasets;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='user' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.[user];

    
-- Stored Procedures
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='adtlog' AND ROUTINE_NAME='uspMoveStagingToAuditLog' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE adtlog.uspMoveStagingToAuditLog;