
CREATE TABLE [dbo].[account](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[address1_addresstypecode] [int] NULL,
	[msdyn_travelchargetype] [int] NULL,
	[address1_shippingmethodcode] [int] NULL,
	[accountcategorycode] [int] NULL,
	[address1_freighttermscode] [int] NULL,
	[preferredappointmenttimecode] [int] NULL,
	[accountclassificationcode] [int] NULL,
	[customertypecode] [int] NULL,
	[ownershipcode] [int] NULL,
	[territorycode] [int] NULL,
	[industrycode] [int] NULL,
	[businesstypecode] [int] NULL,
	[shippingmethodcode] [int] NULL,
	[paymenttermscode] [int] NULL,
	[accountratingcode] [int] NULL,
	[address2_addresstypecode] [int] NULL,
	[customersizecode] [int] NULL,
	[preferredcontactmethodcode] [int] NULL,
	[address2_shippingmethodcode] [int] NULL,
	[preferredappointmentdaycode] [int] NULL,
	[address2_freighttermscode] [int] NULL,
	[donotpostalmail] [bit] NULL,
	[donotsendmm] [bit] NULL,
	[creditonhold] [bit] NULL,
	[donotbulkpostalmail] [bit] NULL,
	[isprivate] [bit] NULL,
	[donotbulkemail] [bit] NULL,
	[donotfax] [bit] NULL,
	[donotemail] [bit] NULL,
	[donotphone] [bit] NULL,
	[marketingonly] [bit] NULL,
	[merged] [bit] NULL,
	[followemail] [bit] NULL,
	[participatesinworkflow] [bit] NULL,
	[msdyn_taxexempt] [bit] NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[originatingleadid] [uniqueidentifier] NULL,
	[originatingleadid_entitytype] [nvarchar](128) NULL,
	[territoryid] [uniqueidentifier] NULL,
	[territoryid_entitytype] [nvarchar](128) NULL,
	[primarycontactid] [uniqueidentifier] NULL,
	[primarycontactid_entitytype] [nvarchar](128) NULL,
	[parentaccountid] [uniqueidentifier] NULL,
	[parentaccountid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_preferredresource] [uniqueidentifier] NULL,
	[msdyn_preferredresource_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_billingaccount] [uniqueidentifier] NULL,
	[msdyn_billingaccount_entitytype] [nvarchar](128) NULL,
	[createdbyexternalparty] [uniqueidentifier] NULL,
	[createdbyexternalparty_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[preferredequipmentid] [uniqueidentifier] NULL,
	[preferredequipmentid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[masterid] [uniqueidentifier] NULL,
	[masterid_entitytype] [nvarchar](128) NULL,
	[modifiedbyexternalparty] [uniqueidentifier] NULL,
	[modifiedbyexternalparty_entitytype] [nvarchar](128) NULL,
	[defaultpricelevelid] [uniqueidentifier] NULL,
	[defaultpricelevelid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[preferredserviceid] [uniqueidentifier] NULL,
	[preferredserviceid_entitytype] [nvarchar](128) NULL,
	[msdyn_salestaxcode] [uniqueidentifier] NULL,
	[msdyn_salestaxcode_entitytype] [nvarchar](128) NULL,
	[preferredsystemuserid] [uniqueidentifier] NULL,
	[preferredsystemuserid_entitytype] [nvarchar](128) NULL,
	[msdyn_serviceterritory] [uniqueidentifier] NULL,
	[msdyn_serviceterritory_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[aging90] [decimal](38, 2) NULL,
	[openrevenue] [decimal](38, 2) NULL,
	[aging30] [decimal](38, 2) NULL,
	[msdyn_travelcharge_base] [decimal](38, 2) NULL,
	[aging60_base] [decimal](38, 4) NULL,
	[creditlimit] [decimal](38, 2) NULL,
	[openrevenue_base] [decimal](38, 2) NULL,
	[revenue] [decimal](38, 2) NULL,
	[marketcap] [decimal](38, 2) NULL,
	[aging60] [decimal](38, 2) NULL,
	[msdyn_travelcharge] [decimal](38, 2) NULL,
	[creditlimit_base] [decimal](38, 4) NULL,
	[revenue_base] [decimal](38, 4) NULL,
	[aging90_base] [decimal](38, 4) NULL,
	[marketcap_base] [decimal](38, 4) NULL,
	[aging30_base] [decimal](38, 4) NULL,
	[emailaddress3] [nvarchar](100) NULL,
	[emailaddress2] [nvarchar](100) NULL,
	[emailaddress1] [nvarchar](100) NULL,
	[masteraccountidyominame] [nvarchar](100) NULL,
	[address1_city] [nvarchar](80) NULL,
	[address1_longitude] [decimal](38, 5) NULL,
	[modifiedon] [datetime] NULL,
	[overriddencreatedon] [datetime] NULL,
	[websiteurl] [nvarchar](200) NULL,
	[sharesoutstanding] [int] NULL,
	[primarycontactidname] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[msdyn_salestaxcodename] [nvarchar](100) NULL,
	[preferredsystemuseridyominame] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[opendeals_date] [datetime] NULL,
	[modifiedbyexternalpartyyominame] [nvarchar](100) NULL,
	[masteraccountidname] [nvarchar](100) NULL,
	[preferredsystemuseridname] [nvarchar](100) NULL,
	[address2_stateorprovince] [nvarchar](50) NULL,
	[address2_country] [nvarchar](80) NULL,
	[address2_line2] [nvarchar](250) NULL,
	[msdyn_preferredresourcename] [nvarchar](100) NULL,
	[address1_line3] [nvarchar](250) NULL,
	[onholdtime] [int] NULL,
	[parentaccountidname] [nvarchar](100) NULL,
	[originatingleadidname] [nvarchar](100) NULL,
	[address1_utcoffset] [int] NULL,
	[numberofemployees] [int] NULL,
	[modifiedbyexternalpartyname] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[address2_county] [nvarchar](50) NULL,
	[telephone3] [nvarchar](50) NULL,
	[address2_city] [nvarchar](80) NULL,
	[msdyn_taxexemptnumber] [nvarchar](20) NULL,
	[address2_latitude] [decimal](38, 5) NULL,
	[createdon] [datetime] NULL,
	[address2_line1] [nvarchar](250) NULL,
	[address1_composite] [nvarchar](max) NULL,
	[opendeals_state] [int] NULL,
	[address2_postalcode] [nvarchar](20) NULL,
	[lastusedincampaign] [datetime] NULL,
	[processid] [uniqueidentifier] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[address2_line3] [nvarchar](250) NULL,
	[description] [nvarchar](max) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[address1_county] [nvarchar](50) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[address1_line1] [nvarchar](250) NULL,
	[address2_postofficebox] [nvarchar](20) NULL,
	[address2_telephone1] [nvarchar](50) NULL,
	[address2_telephone2] [nvarchar](50) NULL,
	[address2_telephone3] [nvarchar](50) NULL,
	[originatingleadidyominame] [nvarchar](100) NULL,
	[address1_addressid] [uniqueidentifier] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[territoryidname] [nvarchar](100) NULL,
	[yominame] [nvarchar](160) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[address2_name] [nvarchar](200) NULL,
	[openrevenue_state] [int] NULL,
	[primarysatoriid] [nvarchar](200) NULL,
	[name] [nvarchar](160) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[timespentbymeonemailandmeetings] [nvarchar](1250) NULL,
	[primarytwitterid] [nvarchar](20) NULL,
	[owneridname] [nvarchar](100) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[address2_composite] [nvarchar](max) NULL,
	[address1_country] [nvarchar](80) NULL,
	[address1_stateorprovince] [nvarchar](50) NULL,
	[createdbyexternalpartyyominame] [nvarchar](100) NULL,
	[msdyn_billingaccountyominame] [nvarchar](100) NULL,
	[address1_telephone1] [nvarchar](50) NULL,
	[address1_telephone2] [nvarchar](50) NULL,
	[address1_telephone3] [nvarchar](50) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[address1_postofficebox] [nvarchar](20) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[fax] [nvarchar](50) NULL,
	[sic] [nvarchar](20) NULL,
	[address2_utcoffset] [int] NULL,
	[stageid] [uniqueidentifier] NULL,
	[accountnumber] [nvarchar](20) NULL,
	[address2_fax] [nvarchar](50) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[address2_longitude] [decimal](38, 5) NULL,
	[ftpsiteurl] [nvarchar](200) NULL,
	[preferredequipmentidname] [nvarchar](100) NULL,
	[defaultpricelevelidname] [nvarchar](100) NULL,
	[address1_primarycontactname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[address1_line2] [nvarchar](250) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[openrevenue_date] [datetime] NULL,
	[address2_upszone] [nvarchar](4) NULL,
	[address1_postalcode] [nvarchar](20) NULL,
	[tickersymbol] [nvarchar](10) NULL,
	[preferredserviceidname] [nvarchar](100) NULL,
	[createdbyexternalpartyname] [nvarchar](100) NULL,
	[msdyn_serviceterritoryname] [nvarchar](100) NULL,
	[stockexchange] [nvarchar](20) NULL,
	[msdyn_billingaccountname] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[msdyn_workorderinstructions] [nvarchar](max) NULL,
	[telephone2] [nvarchar](50) NULL,
	[versionnumber] [bigint] NULL,
	[accountid] [uniqueidentifier] NULL,
	[telephone1] [nvarchar](50) NULL,
	[address1_name] [nvarchar](200) NULL,
	[address1_fax] [nvarchar](50) NULL,
	[address1_latitude] [decimal](38, 5) NULL,
	[primarycontactidyominame] [nvarchar](100) NULL,
	[new_test] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[address1_upszone] [nvarchar](4) NULL,
	[address2_addressid] [uniqueidentifier] NULL,
	[slaname] [nvarchar](100) NULL,
	[parentaccountidyominame] [nvarchar](100) NULL,
	[address2_primarycontactname] [nvarchar](100) NULL,
	[opendeals] [int] NULL)



CREATE TABLE [dbo].[bookableresource](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_startlocation] [int] NULL,
	[msdyn_generictype] [int] NULL,
	[resourcetype] [int] NULL,
	[msdyn_endlocation] [int] NULL,
	[msdyn_timeoffapprovalrequired] [bit] NULL,
	[msdyn_displayonscheduleassistant] [bit] NULL,
	[msdyn_enabledripscheduling] [bit] NULL,
	[msdyn_displayonscheduleboard] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[contactid] [uniqueidentifier] NULL,
	[contactid_entitytype] [nvarchar](128) NULL,
	[msdyn_organizationalunit] [uniqueidentifier] NULL,
	[msdyn_organizationalunit_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[userid] [uniqueidentifier] NULL,
	[userid_entitytype] [nvarchar](128) NULL,
	[msdyn_warehouse] [uniqueidentifier] NULL,
	[msdyn_warehouse_entitytype] [nvarchar](128) NULL,
	[calendarid] [uniqueidentifier] NULL,
	[calendarid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[accountid] [uniqueidentifier] NULL,
	[accountid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_hourlyrate] [decimal](38, 2) NULL,
	[msdyn_hourlyrate_base] [decimal](38, 2) NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[timezone] [int] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[modifiedon] [datetime] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_primaryemail] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[useridyominame] [nvarchar](100) NULL,
	[accountidyominame] [nvarchar](100) NULL,
	[calendaridname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_warehousename] [nvarchar](100) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[contactidname] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_organizationalunitname] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[msdyn_bookingstodrip] [int] NULL,
	[processid] [uniqueidentifier] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[stageid] [uniqueidentifier] NULL,
	[bookableresourceid] [uniqueidentifier] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[useridname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[name] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[accountidname] [nvarchar](100) NULL,
	[contactidyominame] [nvarchar](100) NULL)

CREATE TABLE [dbo].[bookableresourcebooking](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_bookingmethod] [int] NULL,
	[bookingtype] [int] NULL,
	[msdyn_traveltimerescheduling] [bit] NULL,
	[msdyn_allowoverlapping] [bit] NULL,
	[msdyn_cascadecrewchanges] [bit] NULL,
	[msdyn_preventtimestampcreation] [bit] NULL,
	[resource] [uniqueidentifier] NULL,
	[resource_entitytype] [nvarchar](128) NULL,
	[msdyn_bookingsetupmetadataid] [uniqueidentifier] NULL,
	[msdyn_bookingsetupmetadataid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[bookingstatus] [uniqueidentifier] NULL,
	[bookingstatus_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[msdyn_resourcerequirement] [uniqueidentifier] NULL,
	[msdyn_resourcerequirement_entitytype] [nvarchar](128) NULL,
	[msdyn_agreementbookingdate] [uniqueidentifier] NULL,
	[msdyn_agreementbookingdate_entitytype] [nvarchar](128) NULL,
	[header] [uniqueidentifier] NULL,
	[header_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[msdyn_timegroupdetailselected] [uniqueidentifier] NULL,
	[msdyn_timegroupdetailselected_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_workorder] [uniqueidentifier] NULL,
	[msdyn_workorder_entitytype] [nvarchar](128) NULL,
	[msdyn_resourcegroup] [uniqueidentifier] NULL,
	[msdyn_resourcegroup_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_totalcost] [decimal](38, 2) NULL,
	[msdyn_totalcost_base] [decimal](38, 2) NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[modifiedon] [datetime] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[endtime] [datetime] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[msdyn_actualtravelduration] [int] NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_totaldurationinprogress] [int] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[msdyn_resourcerequirementname] [nvarchar](100) NULL,
	[msdyn_slottext] [nvarchar](max) NULL,
	[msdyn_milestraveled] [decimal](38, 2) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_bookingsetupmetadataidname] [nvarchar](100) NULL,
	[headername] [nvarchar](100) NULL,
	[msdyn_estimatedarrivaltime] [datetime] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_totalbillableduration] [int] NULL,
	[starttime] [datetime] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[duration] [int] NULL,
	[msdyn_workordername] [nvarchar](100) NULL,
	[processid] [uniqueidentifier] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[msdyn_estimatedtravelduration] [int] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[stageid] [uniqueidentifier] NULL,
	[msdyn_agreementbookingdatename] [nvarchar](100) NULL,
	[msdyn_timegroupdetailselectedname] [nvarchar](100) NULL,
	[resourcename] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[msdyn_latitude] [decimal](38, 5) NULL,
	[bookableresourcebookingid] [uniqueidentifier] NULL,
	[bookingstatusname] [nvarchar](100) NULL,
	[msdyn_actualarrivaltime] [datetime] NULL,
	[name] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_longitude] [decimal](38, 5) NULL,
	[msdyn_signature] [nvarchar](max) NULL,
	[msdyn_internalflags] [nvarchar](max) NULL,
	[msdyn_totalbreakduration] [int] NULL,
	[msdyn_resourcegroupname] [nvarchar](100) NULL)

CREATE TABLE [dbo].[bookingstatus](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[status] [int] NULL,
	[msdyn_fieldservicestatus] [int] NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[description] [nvarchar](100) NULL,
	[msdyn_imageurl] [nvarchar](200) NULL,
	[name] [nvarchar](100) NULL,
	[msdyn_statuscolor] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[bookingstatusid] [uniqueidentifier] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[timezoneruleversionnumber] [int] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_internalflags] [nvarchar](max) NULL,
	[overriddencreatedon] [datetime] NULL)


CREATE TABLE [dbo].[GlobalOptionSetMetadata](
	[OptionSetName] [nvarchar](64) NOT NULL,
	[Option] [int] NOT NULL,
	[IsUserLocalizedLabel] [bit] NOT NULL,
	[LocalizedLabelLanguageCode] [int] NOT NULL,
	[LocalizedLabel] [nvarchar](256) NULL)


CREATE TABLE [dbo].[msdyn_customerasset](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_product] [uniqueidentifier] NULL,
	[msdyn_product_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_account] [uniqueidentifier] NULL,
	[msdyn_account_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_workorderproduct] [uniqueidentifier] NULL,
	[msdyn_workorderproduct_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[msdyn_parentasset] [uniqueidentifier] NULL,
	[msdyn_parentasset_entitytype] [nvarchar](128) NULL,
	[msdyn_masterasset] [uniqueidentifier] NULL,
	[msdyn_masterasset_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_masterassetname] [nvarchar](100) NULL,
	[msdyn_name] [nvarchar](100) NULL,
	[msdyn_workorderproductname] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[msdyn_accountyominame] [nvarchar](100) NULL,
	[msdyn_parentassetname] [nvarchar](100) NULL,
	[msdyn_longitude] [decimal](38, 5) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_customerassetid] [uniqueidentifier] NULL,
	[msdyn_latitude] [decimal](38, 5) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_accountname] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[owneridname] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[msdyn_productname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL)


CREATE TABLE [dbo].[msdyn_incidenttype](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_copyincidentitemstoagreement] [bit] NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[msdyn_defaultworkordertype] [uniqueidentifier] NULL,
	[msdyn_defaultworkordertype_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_defaultworkordertypename] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[msdyn_estimatedduration] [int] NULL,
	[msdyn_name] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[msdyn_incidenttypeid] [uniqueidentifier] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[msdyn_description] [nvarchar](max) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL)

CREATE TABLE [dbo].[msdyn_workorder](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_systemstatus] [int] NULL,
	[msdyn_worklocation] [int] NULL,
	[msdyn_isfollowup] [bit] NULL,
	[msdyn_ismobile] [bit] NULL,
	[msdyn_taxable] [bit] NULL,
	[msdyn_followuprequired] [bit] NULL,
	[msdyn_primaryincidenttype] [uniqueidentifier] NULL,
	[msdyn_primaryincidenttype_entitytype] [nvarchar](128) NULL,
	[msdyn_reportedbycontact] [uniqueidentifier] NULL,
	[msdyn_reportedbycontact_entitytype] [nvarchar](128) NULL,
	[msdyn_taxcode] [uniqueidentifier] NULL,
	[msdyn_taxcode_entitytype] [nvarchar](128) NULL,
	[msdyn_parentworkorder] [uniqueidentifier] NULL,
	[msdyn_parentworkorder_entitytype] [nvarchar](128) NULL,
	[msdyn_serviceterritory] [uniqueidentifier] NULL,
	[msdyn_serviceterritory_entitytype] [nvarchar](128) NULL,
	[msdyn_serviceaccount] [uniqueidentifier] NULL,
	[msdyn_serviceaccount_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_timegroup] [uniqueidentifier] NULL,
	[msdyn_timegroup_entitytype] [nvarchar](128) NULL,
	[msdyn_billingaccount] [uniqueidentifier] NULL,
	[msdyn_billingaccount_entitytype] [nvarchar](128) NULL,
	[msdyn_closedby] [uniqueidentifier] NULL,
	[msdyn_closedby_entitytype] [nvarchar](128) NULL,
	[msdyn_pricelist] [uniqueidentifier] NULL,
	[msdyn_pricelist_entitytype] [nvarchar](128) NULL,
	[msdyn_substatus] [uniqueidentifier] NULL,
	[msdyn_substatus_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[msdyn_customerasset] [uniqueidentifier] NULL,
	[msdyn_customerasset_entitytype] [nvarchar](128) NULL,
	[msdyn_preferredresource] [uniqueidentifier] NULL,
	[msdyn_preferredresource_entitytype] [nvarchar](128) NULL,
	[msdyn_workordertype] [uniqueidentifier] NULL,
	[msdyn_workordertype_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_priority] [uniqueidentifier] NULL,
	[msdyn_priority_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_agreement] [uniqueidentifier] NULL,
	[msdyn_agreement_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_opportunityid] [uniqueidentifier] NULL,
	[msdyn_opportunityid_entitytype] [nvarchar](128) NULL,
	[msdyn_servicerequest] [uniqueidentifier] NULL,
	[msdyn_servicerequest_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[msdyn_timegroupdetailselected] [uniqueidentifier] NULL,
	[msdyn_timegroupdetailselected_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_totalamount] [decimal](38, 2) NULL,
	[msdyn_estimatesubtotalamount] [decimal](38, 2) NULL,
	[msdyn_totalamount_base] [decimal](38, 2) NULL,
	[msdyn_estimatesubtotalamount_base] [decimal](38, 2) NULL,
	[msdyn_subtotalamount] [decimal](38, 2) NULL,
	[msdyn_subtotalamount_base] [decimal](38, 2) NULL,
	[msdyn_totalsalestax_base] [decimal](38, 2) NULL,
	[msdyn_totalsalestax] [decimal](38, 2) NULL,
	[msdyn_primaryincidenttypename] [nvarchar](100) NULL,
	[msdyn_timetopromised] [datetime] NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[msdyn_opportunityidname] [nvarchar](100) NULL,
	[msdyn_closedbyyominame] [nvarchar](100) NULL,
	[msdyn_serviceaccountname] [nvarchar](100) NULL,
	[msdyn_city] [nvarchar](80) NULL,
	[msdyn_name] [nvarchar](100) NULL,
	[msdyn_servicerequestname] [nvarchar](100) NULL,
	[msdyn_primaryincidentdescription] [nvarchar](max) NULL,
	[modifiedon] [datetime] NULL,
	[owneridname] [nvarchar](100) NULL,
	[msdyn_addressname] [nvarchar](250) NULL,
	[msdyn_timewindowstart] [datetime] NULL,
	[msdyn_reportedbycontactyominame] [nvarchar](100) NULL,
	[msdyn_workorderid] [uniqueidentifier] NULL,
	[msdyn_followupnote] [nvarchar](max) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[msdyn_billingaccountname] [nvarchar](100) NULL,
	[msdyn_preferredresourcename] [nvarchar](100) NULL,
	[msdyn_workordertypename] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_datewindowend] [datetime] NULL,
	[msdyn_address3] [nvarchar](250) NULL,
	[msdyn_priorityname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_parentworkordername] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[msdyn_timewindowend] [datetime] NULL,
	[msdyn_customerassetname] [nvarchar](100) NULL,
	[msdyn_primaryincidentestimatedduration] [int] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_instructions] [nvarchar](max) NULL,
	[msdyn_agreementname] [nvarchar](100) NULL,
	[msdyn_serviceaccountyominame] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[msdyn_bookingsummary] [nvarchar](max) NULL,
	[processid] [uniqueidentifier] NULL,
	[msdyn_serviceterritoryname] [nvarchar](100) NULL,
	[msdyn_postalcode] [nvarchar](20) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[msdyn_taxcodename] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_address2] [nvarchar](250) NULL,
	[msdyn_datewindowstart] [datetime] NULL,
	[msdyn_country] [nvarchar](80) NULL,
	[stageid] [uniqueidentifier] NULL,
	[msdyn_reportedbycontactname] [nvarchar](100) NULL,
	[msdyn_workordersummary] [nvarchar](max) NULL,
	[msdyn_timegroupdetailselectedname] [nvarchar](100) NULL,
	[msdyn_timefrompromised] [datetime] NULL,
	[msdyn_timeclosed] [datetime] NULL,
	[msdyn_pricelistname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[msdyn_timegroupname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_latitude] [decimal](38, 5) NULL,
	[msdyn_closedbyname] [nvarchar](100) NULL,
	[msdyn_internalflags] [nvarchar](max) NULL,
	[msdyn_stateorprovince] [nvarchar](50) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_longitude] [decimal](38, 5) NULL,
	[msdyn_billingaccountyominame] [nvarchar](100) NULL,
	[msdyn_childindex] [int] NULL,
	[msdyn_address1] [nvarchar](250) NULL,
	[msdyn_substatusname] [nvarchar](100) NULL)

CREATE TABLE [dbo].[msdyn_workorderproduct](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_linestatus] [int] NULL,
	[msdyn_allocated] [bit] NULL,
	[msdyn_taxable] [bit] NULL,
	[msdyn_warehouse] [uniqueidentifier] NULL,
	[msdyn_warehouse_entitytype] [nvarchar](128) NULL,
	[msdyn_workorderincident] [uniqueidentifier] NULL,
	[msdyn_workorderincident_entitytype] [nvarchar](128) NULL,
	[msdyn_unit] [uniqueidentifier] NULL,
	[msdyn_unit_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_booking] [uniqueidentifier] NULL,
	[msdyn_booking_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[msdyn_customerasset] [uniqueidentifier] NULL,
	[msdyn_customerasset_entitytype] [nvarchar](128) NULL,
	[msdyn_pricelist] [uniqueidentifier] NULL,
	[msdyn_pricelist_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_product] [uniqueidentifier] NULL,
	[msdyn_product_entitytype] [nvarchar](128) NULL,
	[msdyn_purchaseorderreceiptproduct] [uniqueidentifier] NULL,
	[msdyn_purchaseorderreceiptproduct_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_workorder] [uniqueidentifier] NULL,
	[msdyn_workorder_entitytype] [nvarchar](128) NULL,
	[msdyn_agreementbookingproduct] [uniqueidentifier] NULL,
	[msdyn_agreementbookingproduct_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_estimateunitcost_base] [decimal](38, 2) NULL,
	[msdyn_estimateunitcost] [decimal](38, 2) NULL,
	[msdyn_discountamount] [decimal](38, 2) NULL,
	[msdyn_unitcost] [decimal](38, 2) NULL,
	[msdyn_estimatetotalcost_base] [decimal](38, 2) NULL,
	[msdyn_estimatesubtotal_base] [decimal](38, 2) NULL,
	[msdyn_totalamount] [decimal](38, 2) NULL,
	[msdyn_subtotal_base] [decimal](38, 2) NULL,
	[msdyn_additionalcost_base] [decimal](38, 2) NULL,
	[msdyn_unitamount] [decimal](38, 2) NULL,
	[msdyn_estimatediscountamount_base] [decimal](38, 2) NULL,
	[msdyn_estimatetotalamount] [decimal](38, 2) NULL,
	[msdyn_commissioncosts] [decimal](38, 2) NULL,
	[msdyn_unitamount_base] [decimal](38, 2) NULL,
	[msdyn_totalamount_base] [decimal](38, 2) NULL,
	[msdyn_totalcost_base] [decimal](38, 2) NULL,
	[msdyn_subtotal] [decimal](38, 2) NULL,
	[msdyn_estimatetotalcost] [decimal](38, 2) NULL,
	[msdyn_commissioncosts_base] [decimal](38, 2) NULL,
	[msdyn_additionalcost] [decimal](38, 2) NULL,
	[msdyn_estimateunitamount] [decimal](38, 2) NULL,
	[msdyn_estimateunitamount_base] [decimal](38, 2) NULL,
	[msdyn_unitcost_base] [decimal](38, 2) NULL,
	[msdyn_estimatediscountamount] [decimal](38, 2) NULL,
	[msdyn_estimatesubtotal] [decimal](38, 2) NULL,
	[msdyn_discountamount_base] [decimal](38, 2) NULL,
	[msdyn_totalcost] [decimal](38, 2) NULL,
	[msdyn_estimatetotalamount_base] [decimal](38, 2) NULL,
	[msdyn_quantity] [decimal](38, 2) NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[msdyn_description] [nvarchar](max) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[msdyn_workorderincidentname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[msdyn_workorderproductid] [uniqueidentifier] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_qtytobill] [decimal](38, 2) NULL,
	[msdyn_customerassetname] [nvarchar](100) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_unitname] [nvarchar](100) NULL,
	[msdyn_lineorder] [int] NULL,
	[modifiedon] [datetime] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[msdyn_productname] [nvarchar](100) NULL,
	[msdyn_workordername] [nvarchar](100) NULL,
	[msdyn_estimatediscountpercent] [decimal](38, 2) NULL,
	[msdyn_name] [nvarchar](200) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_internaldescription] [nvarchar](max) NULL,
	[msdyn_bookingname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_estimatequantity] [decimal](38, 2) NULL,
	[msdyn_pricelistname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[msdyn_agreementbookingproductname] [nvarchar](100) NULL,
	[msdyn_internalflags] [nvarchar](max) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[msdyn_warehousename] [nvarchar](100) NULL,
	[msdyn_discountpercent] [decimal](38, 2) NULL,
	[msdyn_purchaseorderreceiptproductname] [nvarchar](100) NULL)

CREATE TABLE [dbo].[msdyn_workorderservice](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_linestatus] [int] NULL,
	[msdyn_taxable] [bit] NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_workorderincident] [uniqueidentifier] NULL,
	[msdyn_workorderincident_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[msdyn_agreementbookingservice] [uniqueidentifier] NULL,
	[msdyn_agreementbookingservice_entitytype] [nvarchar](128) NULL,
	[msdyn_customerasset] [uniqueidentifier] NULL,
	[msdyn_customerasset_entitytype] [nvarchar](128) NULL,
	[msdyn_pricelist] [uniqueidentifier] NULL,
	[msdyn_pricelist_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[msdyn_unit] [uniqueidentifier] NULL,
	[msdyn_unit_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_booking] [uniqueidentifier] NULL,
	[msdyn_booking_entitytype] [nvarchar](128) NULL,
	[msdyn_workorder] [uniqueidentifier] NULL,
	[msdyn_workorder_entitytype] [nvarchar](128) NULL,
	[msdyn_service] [uniqueidentifier] NULL,
	[msdyn_service_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_totalamount_base] [decimal](38, 2) NULL,
	[msdyn_estimateunitcost_base] [decimal](38, 2) NULL,
	[msdyn_discountamount] [decimal](38, 2) NULL,
	[msdyn_unitcost] [decimal](38, 2) NULL,
	[msdyn_estimatecalculatedunitamount_base] [decimal](38, 2) NULL,
	[msdyn_estimatetotalcost_base] [decimal](38, 2) NULL,
	[msdyn_estimatesubtotal_base] [decimal](38, 2) NULL,
	[msdyn_commissioncosts_base] [decimal](38, 2) NULL,
	[msdyn_minimumchargeamount] [decimal](38, 2) NULL,
	[msdyn_totalamount] [decimal](38, 2) NULL,
	[msdyn_estimatecalculatedunitamount] [decimal](38, 2) NULL,
	[msdyn_unitamount] [decimal](38, 2) NULL,
	[msdyn_estimatediscountamount_base] [decimal](38, 2) NULL,
	[msdyn_estimatetotalamount] [decimal](38, 2) NULL,
	[msdyn_commissioncosts] [decimal](38, 2) NULL,
	[msdyn_additionalcost_base] [decimal](38, 2) NULL,
	[msdyn_minimumchargeamount_base] [decimal](38, 2) NULL,
	[msdyn_unitamount_base] [decimal](38, 2) NULL,
	[msdyn_calculatedunitamount_base] [decimal](38, 2) NULL,
	[msdyn_subtotal] [decimal](38, 2) NULL,
	[msdyn_estimatetotalcost] [decimal](38, 2) NULL,
	[msdyn_totalcost_base] [decimal](38, 2) NULL,
	[msdyn_additionalcost] [decimal](38, 2) NULL,
	[msdyn_estimateunitamount_base] [decimal](38, 2) NULL,
	[msdyn_unitcost_base] [decimal](38, 2) NULL,
	[msdyn_estimateunitamount] [decimal](38, 2) NULL,
	[msdyn_calculatedunitamount] [decimal](38, 2) NULL,
	[msdyn_estimatediscountamount] [decimal](38, 2) NULL,
	[msdyn_discountamount_base] [decimal](38, 2) NULL,
	[msdyn_totalcost] [decimal](38, 2) NULL,
	[msdyn_estimateunitcost] [decimal](38, 2) NULL,
	[msdyn_estimatesubtotal] [decimal](38, 2) NULL,
	[msdyn_estimatetotalamount_base] [decimal](38, 2) NULL,
	[msdyn_subtotal_base] [decimal](38, 2) NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_agreementbookingservicename] [nvarchar](100) NULL,
	[msdyn_servicename] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[msdyn_description] [nvarchar](max) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[msdyn_workorderserviceid] [uniqueidentifier] NULL,
	[msdyn_workorderincidentname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[msdyn_customerassetname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_durationtobill] [int] NULL,
	[msdyn_pricelistname] [nvarchar](100) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_unitname] [nvarchar](100) NULL,
	[msdyn_lineorder] [int] NULL,
	[modifiedon] [datetime] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[msdyn_workordername] [nvarchar](100) NULL,
	[msdyn_estimatediscountpercent] [decimal](38, 2) NULL,
	[msdyn_name] [nvarchar](200) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_bookingname] [nvarchar](100) NULL,
	[msdyn_estimateduration] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[msdyn_minimumchargeduration] [int] NULL,
	[msdyn_internalflags] [nvarchar](max) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[msdyn_discountpercent] [decimal](38, 2) NULL,
	[msdyn_duration] [int] NULL,
	[msdyn_internaldescription] [nvarchar](max) NULL
)

CREATE TABLE [dbo].[msdyn_workordertype](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_incidentrequired] [bit] NULL,
	[msdyn_taxable] [bit] NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[msdyn_pricelist] [uniqueidentifier] NULL,
	[msdyn_pricelist_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_name] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[msdyn_workordertypeid] [uniqueidentifier] NULL,
	[msdyn_pricelistname] [nvarchar](100) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL
)

CREATE TABLE [dbo].[OptionSetMetadata](
	[EntityName] [nvarchar](64) NOT NULL,
	[OptionSetName] [nvarchar](64) NOT NULL,
	[Option] [int] NOT NULL,
	[IsUserLocalizedLabel] [bit] NOT NULL,
	[LocalizedLabelLanguageCode] [int] NOT NULL,
	[LocalizedLabel] [nvarchar](256) NULL)

CREATE TABLE [dbo].[product](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[productstructure] [int] NULL,
	[producttypecode] [int] NULL,
	[msdyn_fieldserviceproducttype] [int] NULL,
	[iskit] [bit] NULL,
	[msdyn_taxable] [bit] NULL,
	[msdyn_converttocustomerasset] [bit] NULL,
	[isstockitem] [bit] NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[defaultuomscheduleid] [uniqueidentifier] NULL,
	[defaultuomscheduleid_entitytype] [nvarchar](128) NULL,
	[pricelevelid] [uniqueidentifier] NULL,
	[pricelevelid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedbyexternalparty] [uniqueidentifier] NULL,
	[modifiedbyexternalparty_entitytype] [nvarchar](128) NULL,
	[msdyn_defaultvendor] [uniqueidentifier] NULL,
	[msdyn_defaultvendor_entitytype] [nvarchar](128) NULL,
	[parentproductid] [uniqueidentifier] NULL,
	[parentproductid_entitytype] [nvarchar](128) NULL,
	[subjectid] [uniqueidentifier] NULL,
	[subjectid_entitytype] [nvarchar](128) NULL,
	[defaultuomid] [uniqueidentifier] NULL,
	[defaultuomid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdbyexternalparty] [uniqueidentifier] NULL,
	[createdbyexternalparty_entitytype] [nvarchar](128) NULL,
	[organizationid] [uniqueidentifier] NULL,
	[organizationid_entitytype] [nvarchar](128) NULL,
	[currentcost] [decimal](38, 2) NULL,
	[standardcost_base] [decimal](38, 4) NULL,
	[price_base] [decimal](38, 4) NULL,
	[price] [decimal](38, 2) NULL,
	[currentcost_base] [decimal](38, 4) NULL,
	[standardcost] [decimal](38, 2) NULL,
	[msdyn_upccode] [nvarchar](50) NULL,
	[productid] [uniqueidentifier] NULL,
	[entityimage_timestamp] [bigint] NULL,
	[createdon] [datetime] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[parentproductidname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[defaultuomidname] [nvarchar](100) NULL,
	[validfromdate] [datetime] NULL,
	[modifiedbyexternalpartyname] [nvarchar](100) NULL,
	[defaultuomscheduleidname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[overriddencreatedon] [datetime] NULL,
	[producturl] [nvarchar](255) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[size] [nvarchar](200) NULL,
	[versionnumber] [bigint] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[modifiedbyexternalpartyyominame] [nvarchar](100) NULL,
	[msdyn_defaultvendoryominame] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[vendorname] [nvarchar](100) NULL,
	[vendorpartnumber] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[importsequencenumber] [int] NULL,
	[createdbyexternalpartyname] [nvarchar](100) NULL,
	[processid] [uniqueidentifier] NULL,
	[description] [nvarchar](max) NULL,
	[msdyn_defaultvendorname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[subjectidname] [nvarchar](100) NULL,
	[stageid] [uniqueidentifier] NULL,
	[stockvolume] [decimal](38, 2) NULL,
	[quantitydecimal] [int] NULL,
	[quantityonhand] [decimal](38, 2) NULL,
	[pricelevelidname] [nvarchar](100) NULL,
	[msdyn_purchasename] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[vendorid] [nvarchar](100) NULL,
	[hierarchypath] [nvarchar](450) NULL,
	[suppliername] [nvarchar](100) NULL,
	[validtodate] [datetime] NULL,
	[name] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[stockweight] [decimal](38, 2) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[dmtimportstate] [int] NULL,
	[productnumber] [nvarchar](100) NULL,
	[createdbyexternalpartyyominame] [nvarchar](100) NULL,
	[organizationidname] [nvarchar](100) NULL
)

CREATE TABLE [dbo].[resource](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[isdisabled] [bit] NULL,
	[displayinserviceviews] [bit] NULL,
	[organizationid] [uniqueidentifier] NULL,
	[organizationid_entitytype] [nvarchar](128) NULL,
	[siteid] [uniqueidentifier] NULL,
	[siteid_entitytype] [nvarchar](128) NULL,
	[businessunitid] [uniqueidentifier] NULL,
	[businessunitid_entitytype] [nvarchar](128) NULL,
	[siteidname] [nvarchar](100) NULL,
	[calendarid] [uniqueidentifier] NULL,
	[versionnumber] [bigint] NULL,
	[organizationidname] [nvarchar](100) NULL,
	[resourceid] [uniqueidentifier] NULL,
	[entityimage_timestamp] [bigint] NULL,
	[businessunitidname] [nvarchar](100) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[objecttypecode] [nvarchar](4000) NULL,
	[name] [nvarchar](160) NULL,
	[entityimage_url] [nvarchar](200) NULL
)

CREATE TABLE [dbo].[service](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[initialstatuscode] [int] NULL,
	[isvisible] [bit] NULL,
	[isschedulable] [bit] NULL,
	[showresources] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[resourcespecid] [uniqueidentifier] NULL,
	[resourcespecid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[strategyid] [uniqueidentifier] NULL,
	[strategyid_entitytype] [nvarchar](128) NULL,
	[organizationid] [uniqueidentifier] NULL,
	[organizationid_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[granularity] [nvarchar](100) NULL,
	[name] [nvarchar](160) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[importsequencenumber] [int] NULL,
	[organizationidname] [nvarchar](100) NULL,
	[duration] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[resourcespecidname] [nvarchar](100) NULL,
	[calendarid] [uniqueidentifier] NULL,
	[modifiedon] [datetime] NULL,
	[anchoroffset] [int] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[description] [nvarchar](max) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL
)

CREATE TABLE [dbo].[serviceappointment](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[ismapiprivate] [bit] NULL,
	[isalldayevent] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[siteid] [uniqueidentifier] NULL,
	[siteid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[customers] [uniqueidentifier] NULL,
	[resources] [uniqueidentifier] NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[onholdtime] [int] NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[scheduledstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subcategory] [nvarchar](250) NULL,
	[description] [nvarchar](max) NULL,
	[overriddencreatedon] [datetime] NULL,
	[subject] [nvarchar](200) NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[actualstart] [datetime] NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[siteidname] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[scheduleddurationminutes] [int] NULL,
	[sortdate] [datetime] NULL,
	[slaname] [nvarchar](100) NULL,
	[location] [nvarchar](500) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[modifiedon] [datetime] NULL,
	[category] [nvarchar](250) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[activityid] [uniqueidentifier] NULL,
	[serviceidname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[scheduledend] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL
)

CREATE TABLE [dbo].[StateMetadata](
	[EntityName] [nvarchar](64) NOT NULL,
	[State] [int] NOT NULL,
	[IsUserLocalizedLabel] [bit] NOT NULL,
	[LocalizedLabelLanguageCode] [int] NOT NULL,
	[LocalizedLabel] [nvarchar](256) NULL
)

CREATE TABLE [dbo].[StatusMetadata](
	[EntityName] [nvarchar](64) NOT NULL,
	[State] [int] NOT NULL,
	[Status] [int] NOT NULL,
	[IsUserLocalizedLabel] [bit] NOT NULL,
	[LocalizedLabelLanguageCode] [int] NOT NULL,
	[LocalizedLabel] [nvarchar](256) NULL
)

CREATE TABLE [dbo].[task](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[crmtaskassigneduniqueid] [uniqueidentifier] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[onholdtime] [int] NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[scheduledstart] [datetime] NULL,
	[actualstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subcategory] [nvarchar](250) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[scheduleddurationminutes] [int] NULL,
	[category] [nvarchar](250) NULL,
	[processid] [uniqueidentifier] NULL,
	[description] [nvarchar](max) NULL,
	[slaname] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[sortdate] [datetime] NULL,
	[lastonholdtime] [datetime] NULL,
	[stageid] [uniqueidentifier] NULL,
	[modifiedon] [datetime] NULL,
	[percentcomplete] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[activityid] [uniqueidentifier] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[scheduledend] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL,
	[subject] [nvarchar](200) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL
)

CREATE TABLE [dbo].[territory](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[managerid] [uniqueidentifier] NULL,
	[managerid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[organizationid] [uniqueidentifier] NULL,
	[organizationid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[manageridname] [nvarchar](100) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[name] [nvarchar](200) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[importsequencenumber] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[territoryid] [uniqueidentifier] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[organizationidname] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[manageridyominame] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[description] [nvarchar](max) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[entityimage_url] [nvarchar](200) NULL
)

/* fso schema specific tables */

CREATE TABLE fso.[configuration]
(
  id                     INT IDENTITY(1, 1) NOT NULL,
  configuration_group    VARCHAR(150) NOT NULL,
  configuration_subgroup VARCHAR(150) NOT NULL,
  name                   VARCHAR(150) NOT NULL,
  value                  VARCHAR(max) NULL,
  visible                BIT NOT NULL DEFAULT 0
);

CREATE TABLE fso.[entityinitialcount](
	[entityname] [nvarchar](40) NULL,
	[initialcount] INT NULL,
	[lastcount] INT NULL,
	[lasttimestamp] DATETIME2 NULL
);


CREATE TABLE [fso].[date](
	[date_key] [int] NOT NULL,
	[full_date] [date] NOT NULL,
	[day_of_week] [tinyint] NOT NULL,
	[day_num_in_month] [tinyint] NOT NULL,
	[day_name] [char](9) NOT NULL,
	[day_abbrev] [char](3) NOT NULL,
	[weekday_flag] [char](1) NOT NULL,
	[week_num_in_year] [tinyint] NOT NULL,
	[week_begin_date] [date] NOT NULL,
	[month] [tinyint] NOT NULL,
	[month_name] [char](9) NOT NULL,
	[month_abbrev] [char](3) NOT NULL,
	[quarter] [tinyint] NOT NULL,
	[year] [smallint] NOT NULL,
	[yearmo] [int] NOT NULL,
	[same_day_year_ago_date] [date] NOT NULL
)
