//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Deployment.Common.ErrorResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnglishErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Deployment.Common.ErrorResources.EnglishErrorCodes", typeof(EnglishErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting the Activity Log to EventHub.
        /// </summary>
        public static string ActivityLogsErrorExportingToEventHub {
            get {
                return ResourceManager.GetString("ActivityLogsErrorExportingToEventHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out occurred while exporting the Activity Log to Event Hub.
        /// </summary>
        public static string ActivityLogsExportEventHubTimeout {
            get {
                return ResourceManager.GetString("ActivityLogsExportEventHubTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while pulling historical Activity Log data.
        /// </summary>
        public static string ActivityLogsGetHistoricalDataError {
            get {
                return ResourceManager.GetString("ActivityLogsGetHistoricalDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has insufficient permissions to export activity logs to Event Hub in this subscription.
        /// </summary>
        public static string ActivityLogsInsufficientPermissions {
            get {
                return ResourceManager.GetString("ActivityLogsInsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out while waiting for the Activity Log Exported Event Hub to become available.
        /// </summary>
        public static string ActivityLogsVerifyInsightsTimeout {
            get {
                return ResourceManager.GetString("ActivityLogsVerifyInsightsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fully provisioned API Management Services were found in your Azure Subscription.
        /// </summary>
        public static string ApiManagementErrorNoServicesFound {
            get {
                return ResourceManager.GetString("ApiManagementErrorNoServicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new API Management Logger.
        /// </summary>
        public static string ApiManagementFailedToCreateLogger {
            get {
                return ResourceManager.GetString("ApiManagementFailedToCreateLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have Administrator privileges for this instance of Dynamics 365.
        /// </summary>
        public static string AxAuthorizationError {
            get {
                return ResourceManager.GetString("AxAuthorizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to your Finance and Operations instance.
        /// </summary>
        public static string AxConnectionError {
            get {
                return ResourceManager.GetString("AxConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you&apos;re not running the correct platform version of Dynamics 365 for Finance and Operations. The template requires at least Platform Update 8..
        /// </summary>
        public static string AxWrongPlatform {
            get {
                return ResourceManager.GetString("AxWrongPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error signing you in.
        /// </summary>
        public static string AzureLoginFailed {
            get {
                return ResourceManager.GetString("AzureLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,the azure token expired, please try again in a new tab.
        /// </summary>
        public static string AzureTokenExpired {
            get {
                return ResourceManager.GetString("AzureTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Azure website name is already taken.
        /// </summary>
        public static string AzureWebsiteNameTaken {
            get {
                return ResourceManager.GetString("AzureWebsiteNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start PowerShell.
        /// </summary>
        public static string CannotStartPowerShell {
            get {
                return ResourceManager.GetString("CannotStartPowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is missing.
        /// </summary>
        public static string CreateTaskPasswordMissing {
            get {
                return ResourceManager.GetString("CreateTaskPasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This particular version of Windows 10 has Credential Guard enabled and a known issue prevents our scheduled job from running correctly. Please disable Credential Guard (https://www.microsoft.com/en-us/download/details.aspx?id=53337) or upgrade to Windows 10 Creators Update..
        /// </summary>
        public static string CredentialGuardEnabled {
            get {
                return ResourceManager.GetString("CredentialGuardEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from the Credential Manager or the entry was not found.
        /// </summary>
        public static string CredMgrReadError {
            get {
                return ResourceManager.GetString("CredMgrReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the Credential Manager.
        /// </summary>
        public static string CredMgrWriteError {
            get {
                return ResourceManager.GetString("CredMgrWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch information from Cuna API..
        /// </summary>
        public static string CunaApiCallFailure {
            get {
                return ResourceManager.GetString("CunaApiCallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuna API returned no reponse..
        /// </summary>
        public static string CunaApiNoResponse {
            get {
                return ResourceManager.GetString("CunaApiNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process response from Cuna.
        /// </summary>
        public static string CunaApiResponseProcessingFailed {
            get {
                return ResourceManager.GetString("CunaApiResponseProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate the authentication token.
        /// </summary>
        public static string CunaAuthTokenValidationFailed {
            get {
                return ResourceManager.GetString("CunaAuthTokenValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Cuna API access token.
        /// </summary>
        public static string CunaGetApiAccessTokenFailed {
            get {
                return ResourceManager.GetString("CunaGetApiAccessTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string CunaInvalidRequest {
            get {
                return ResourceManager.GetString("CunaInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating datapool reference..
        /// </summary>
        public static string DatapoolCreateError {
            get {
                return ResourceManager.GetString("DatapoolCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact us using the provided email link.
        /// </summary>
        public static string DefaultAdditionalDetailsMessage {
            get {
                return ResourceManager.GetString("DefaultAdditionalDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, see additional details to learn more.
        /// </summary>
        public static string DefaultErrorCode {
            get {
                return ResourceManager.GetString("DefaultErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, please check that you have entered in the correct credentials.
        /// </summary>
        public static string DefaultLoginFailed {
            get {
                return ResourceManager.GetString("DefaultLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template requires group policy &quot;Network access: Do not allow storage of passwords and credentials for network authentication&quot; to be disabled.
        /// </summary>
        public static string DisabledDomainCredsEnabled {
            get {
                return ResourceManager.GetString("DisabledDomainCredsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while querying Event Hub access keys.
        /// </summary>
        public static string EventHubFailedToQueryKeys {
            get {
                return ResourceManager.GetString("EventHubFailedToQueryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the pages you entered could not be found.
        /// </summary>
        public static string FacebookPagesInvalid {
            get {
                return ResourceManager.GetString("FacebookPagesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page id or token provided is invalid..
        /// </summary>
        public static string FacebookTokenAuthFailed {
            get {
                return ResourceManager.GetString("FacebookTokenAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed for user.
        /// </summary>
        public static string ImpersonationFailed {
            get {
                return ResourceManager.GetString("ImpersonationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, check that you have entered in the correct Windows credentials.
        /// </summary>
        public static string IncorrectNTCredentials {
            get {
                return ResourceManager.GetString("IncorrectNTCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SQL Tools failed, please verify you are executing the installer as an Administrator.
        /// </summary>
        public static string InstallSQLToolsFailed {
            get {
                return ResourceManager.GetString("InstallSQLToolsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, check that you have entered in the correct TenantID, ClientID, ClientSecret, RefreshToken.
        /// </summary>
        public static string LithiumCredentialsInvalid {
            get {
                return ResourceManager.GetString("LithiumCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell version too low - please upgrade to latest version https://msdn.microsoft.com/en-us/powershell/wmf/5.0/requirements&quot;.
        /// </summary>
        public static string LowPowerShellVersion {
            get {
                return ResourceManager.GetString("LowPowerShellVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate replication profile.
        /// </summary>
        public static string MsCrm_ErrorActivateProfile {
            get {
                return ResourceManager.GetString("MsCrm_ErrorActivateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create replication profile.
        /// </summary>
        public static string MsCrm_ErrorCreateProfile {
            get {
                return ResourceManager.GetString("MsCrm_ErrorCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register the KeyVault as a provider in this subscription.
        /// </summary>
        public static string MsCrm_ErrorRegisterKv {
            get {
                return ResourceManager.GetString("MsCrm_ErrorRegisterKv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read metadata for your Dynamics 365 organization.
        /// </summary>
        public static string MsCrm_MetadataError {
            get {
                return ResourceManager.GetString("MsCrm_MetadataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dynamics 365 organizations were found, verify that your username and password are correct.
        /// </summary>
        public static string MsCrm_No_Organizations {
            get {
                return ResourceManager.GetString("MsCrm_No_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dynamics 365 organization with this URL could be found.
        /// </summary>
        public static string MsCrm_NoOrg {
            get {
                return ResourceManager.GetString("MsCrm_NoOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dynamics 365 organizations were found.
        /// </summary>
        public static string MsCrm_NoOrgs {
            get {
                return ResourceManager.GetString("MsCrm_NoOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have System Administrator privileges for this instance of Dynamics 365.
        /// </summary>
        public static string MsCrm_Unauthorized {
            get {
                return ResourceManager.GetString("MsCrm_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL databases were found in the selected SQL Server.
        /// </summary>
        public static string NoDatabasesFound {
            get {
                return ResourceManager.GetString("NoDatabasesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program needs to be executed as an adminstrator with elevated permissions.
        /// </summary>
        public static string NotAdmin {
            get {
                return ResourceManager.GetString("NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not look like a PSA instance..
        /// </summary>
        public static string NotPSAInstance {
            get {
                return ResourceManager.GetString("NotPSAInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not look like an SCCM database or you do not have read permissions.
        /// </summary>
        public static string NotSccmDB {
            get {
                return ResourceManager.GetString("NotSccmDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Power BI workspace..
        /// </summary>
        public static string PBIWorkspaceCreateFailed {
            get {
                return ResourceManager.GetString("PBIWorkspaceCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PowerApp environments were found for this Azure account.
        /// </summary>
        public static string PowerAppNoEnvironment {
            get {
                return ResourceManager.GetString("PowerAppNoEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Azure account does not have sufficient permissions to register the required provider.
        /// </summary>
        public static string RegisterProviderError {
            get {
                return ResourceManager.GetString("RegisterProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource group with this name already exists.  Please choose another name for a new resource group..
        /// </summary>
        public static string ResourceGroupAlreadyExists {
            get {
                return ResourceManager.GetString("ResourceGroupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run the scheduled task, please check Task Scheduler.
        /// </summary>
        public static string RunningTaskFailed {
            get {
                return ResourceManager.GetString("RunningTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not have read access to one of the following objects: Opportunity, Account, Lead, Product2, OpportunityLineItem, OpportunityStage, User, UserRole. Please check..
        /// </summary>
        public static string SalesforceInvalidType {
            get {
                return ResourceManager.GetString("SalesforceInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, check that you have entered the correct username, password and token..
        /// </summary>
        public static string SalesforceLoginInvalid {
            get {
                return ResourceManager.GetString("SalesforceLoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SCCM scheduled task could not be found.
        /// </summary>
        public static string SccmTaskNotFound {
            get {
                return ResourceManager.GetString("SccmTaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCCM version format has an unexpected format.
        /// </summary>
        public static string SccmVersionFormatUnexpected {
            get {
                return ResourceManager.GetString("SccmVersionFormatUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SCCM version.
        /// </summary>
        public static string SccmVersionNotFound {
            get {
                return ResourceManager.GetString("SccmVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCCM version is lower than expected (should be at least 2012 R2 SP1).
        /// </summary>
        public static string SccmVersionTooLow {
            get {
                return ResourceManager.GetString("SccmVersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scribe organizations with an active Replication Services subscription were found for your account.
        /// </summary>
        public static string Scribe_No_Organizations {
            get {
                return ResourceManager.GetString("Scribe_No_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve source or target database locale IDs.
        /// </summary>
        public static string SQL_CannotRetrieveCollations {
            get {
                return ResourceManager.GetString("SQL_CannotRetrieveCollations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target database&apos;s compatibility level should be at least 100.
        /// </summary>
        public static string SQL_CompatLevelTooLow {
            get {
                return ResourceManager.GetString("SQL_CompatLevelTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target SQL server edition cannot be Express or local DB.
        /// </summary>
        public static string SQL_DenyLocalAndExpress {
            get {
                return ResourceManager.GetString("SQL_DenyLocalAndExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure SQL Data Warehouse is not supported.
        /// </summary>
        public static string SQL_DenyPDW {
            get {
                return ResourceManager.GetString("SQL_DenyPDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error - the SQL configuration values are inconsistent.
        /// </summary>
        public static string SQL_MalformedConfigValues {
            get {
                return ResourceManager.GetString("SQL_MalformedConfigValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error - not all SQL configuration values were specified.
        /// </summary>
        public static string SQL_MissingConfigValues {
            get {
                return ResourceManager.GetString("SQL_MissingConfigValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The datastore does not contain any connection strings.
        /// </summary>
        public static string SQL_NoConnectionsInDatastore {
            get {
                return ResourceManager.GetString("SQL_NoConnectionsInDatastore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target database must have the same locale ID as the source database.
        /// </summary>
        public static string SQL_TargetCollationDoesntMatch {
            get {
                return ResourceManager.GetString("SQL_TargetCollationDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target SQL server must be at least version 2008 R2 SP3.
        /// </summary>
        public static string SQL_VersionTooLow {
            get {
                return ResourceManager.GetString("SQL_VersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Azure Sql database server is already taken.
        /// </summary>
        public static string SqlDatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("SqlDatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to SQL failed.
        /// </summary>
        public static string SqlLoginFailed {
            get {
                return ResourceManager.GetString("SqlLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set a new Stream Analytics Input.
        /// </summary>
        public static string StreamAnalyticsSetInputFailure {
            get {
                return ResourceManager.GetString("StreamAnalyticsSetInputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set Stream Analytics output.
        /// </summary>
        public static string StreamAnalyticsSetOutputFailure {
            get {
                return ResourceManager.GetString("StreamAnalyticsSetOutputFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle the state of the Stream Analytics job.
        /// </summary>
        public static string StreamAnalyticsToggleFailure {
            get {
                return ResourceManager.GetString("StreamAnalyticsToggleFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the Stream Analytics Job query.
        /// </summary>
        public static string StreamAnalyticsUpdateQueryFailure {
            get {
                return ResourceManager.GetString("StreamAnalyticsUpdateQueryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheduled task did not complete successfully.
        /// </summary>
        public static string TaskSchedulerRunFailed {
            get {
                return ResourceManager.GetString("TaskSchedulerRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the accounts you entered could not be found.
        /// </summary>
        public static string TwitterAccountsInvalid {
            get {
                return ResourceManager.GetString("TwitterAccountsInvalid", resourceCulture);
            }
        }
    }
}
