SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Must be executed inside the target database

-- Regular views
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='fb_insights' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.fb_insights;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='fb_metrics' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.fb_metrics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='fb_posts' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.fb_posts;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='fb_post_insights' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.fb_post_insights;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='page' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.[page];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='calendar' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.[calendar];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='Date' AND TABLE_TYPE='VIEW')
    DROP VIEW fbpa.[Date];


-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageContent' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageContent;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageEngagement' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageEngagement;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageImpressions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[PageImpressions];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePost' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePost;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostEngagement' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostEngagement;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostImpressions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostImpressions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostReactions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostReactions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostStoriesAndPeopleTalkingAboutThis' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostStoriesAndPeopleTalkingAboutThis;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageReactions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageReactions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageUserDemographics' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageUserDemographics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageVideoPosts' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageVideoPosts;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageVideoViews' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageVideoViews;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageViews' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageViews;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='Clicks' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.Clicks;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostInfo' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostInfo;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='Error' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.Error;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='Date' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[Date];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='page_metric_unit' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[page_metric_unit];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='page_metric_unit' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[post_metric_unit];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='page_unit' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[page_unit];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='post_unit' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[post_unit];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='period_post' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[period_post];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='period_page' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[period_page];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='type' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[type];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='time' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[time];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PageTable' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PageTable;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostsInfo' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostsInfo;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='PagePostsTo' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.PagePostsTo;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='post_metric_unit' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.post_metric_unit;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='gender_age' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.gender_age;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='configuration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[configuration];


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageContent' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageContent;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageEngagement' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageEngagement;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageImpressions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.[STAGING_PageImpressions];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePost' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePost;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePostEngagement' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePostEngagement;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePostImpressions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePostImpressions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePostReactions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePostReactions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePostStoriesAndPeopleTalkingAboutThis' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePostStoriesAndPeopleTalkingAboutThis;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageReactions' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageReactions;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageUserDemographics' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageUserDemographics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageVideoPosts' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageVideoPosts;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageVideoViews' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageVideoViews;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PageViews' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PageViews;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_Clicks' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_Clicks;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePostsInfo' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePostsInfo;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fbpa' AND TABLE_NAME='STAGING_PagePostsTo' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE fbpa.STAGING_PagePostsTo;


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='fbpa' AND ROUTINE_NAME='Merge' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE fbpa.[Merge];


IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='fbpa')
BEGIN
    EXEC ('CREATE SCHEMA fbpa AUTHORIZATION dbo'); -- Avoid batch error
END;
