//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedditCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelemetryNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelemetryNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedditCore.Properties.TelemetryNames", typeof(TelemetryNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Error.
        /// </summary>
        internal static string HTTP_Error {
            get {
                return ResourceManager.GetString("HTTP_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Get.
        /// </summary>
        internal static string HTTP_Get {
            get {
                return ResourceManager.GetString("HTTP_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in JSON deserialization routine.
        /// </summary>
        internal static string HTTP_JSON_Error {
            get {
                return ResourceManager.GetString("HTTP_JSON_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Retries.
        /// </summary>
        internal static string HTTP_RetryCount {
            get {
                return ResourceManager.GetString("HTTP_RetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Try.
        /// </summary>
        internal static string HTTP_Try {
            get {
                return ResourceManager.GetString("HTTP_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data found for AzureML.
        /// </summary>
        internal static string ScheduledAzureMLProcessor_DataFound {
            get {
                return ResourceManager.GetString("ScheduledAzureMLProcessor_DataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new data found for AzureML.
        /// </summary>
        internal static string ScheduledAzureMLProcessor_NoDataFound {
            get {
                return ResourceManager.GetString("ScheduledAzureMLProcessor_NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialGist Search.
        /// </summary>
        internal static string SocialGist_Search {
            get {
                return ResourceManager.GetString("SocialGist_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialGist Thread.
        /// </summary>
        internal static string SocialGist_Thread {
            get {
                return ResourceManager.GetString("SocialGist_Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads In Batch.
        /// </summary>
        internal static string ThreadProcessor_BatchSize {
            get {
                return ResourceManager.GetString("ThreadProcessor_BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Comment Count.
        /// </summary>
        internal static string ThreadProcessor_FilteredCommentCount {
            get {
                return ResourceManager.GetString("ThreadProcessor_FilteredCommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Comments and Posts.
        /// </summary>
        internal static string ThreadProcessor_FilteredCommentsAndPostsEvent {
            get {
                return ResourceManager.GetString("ThreadProcessor_FilteredCommentsAndPostsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Post Count.
        /// </summary>
        internal static string ThreadProcessor_FilteredPostCount {
            get {
                return ResourceManager.GetString("ThreadProcessor_FilteredPostCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum ID.
        /// </summary>
        internal static string ThreadProcessor_ForumId {
            get {
                return ResourceManager.GetString("ThreadProcessor_ForumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Thread.
        /// </summary>
        internal static string ThreadProcessor_ProcessThread {
            get {
                return ResourceManager.GetString("ThreadProcessor_ProcessThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread ID.
        /// </summary>
        internal static string ThreadProcessor_ThreadId {
            get {
                return ResourceManager.GetString("ThreadProcessor_ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfiltered Comments.
        /// </summary>
        internal static string ThreadProcessor_UnfilteredComments {
            get {
                return ResourceManager.GetString("ThreadProcessor_UnfilteredComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfiltered Posts.
        /// </summary>
        internal static string ThreadProcessor_UnfilteredPosts {
            get {
                return ResourceManager.GetString("ThreadProcessor_UnfilteredPosts", resourceCulture);
            }
        }
    }
}
