SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;

CREATE TABLE dbo.optionsetmetadata
(
	entityname                 NVARCHAR(64) NOT NULL,
	optionsetname              NVARCHAR(64) NOT NULL,
	[option]                   INT NOT NULL,
	isuserlocalizedlabel       BIT NOT NULL,
	localizedlabellanguagecode INT NOT NULL,
	localizedlabel             NVARCHAR(256) NULL,
	PRIMARY KEY CLUSTERED ( entityname, optionsetname, [option], isuserlocalizedlabel, localizedlabellanguagecode )
);


CREATE TABLE dbo.statusmetadata
(
 entityname                 NVARCHAR(64) NOT NULL,
 [state]                    INT NOT NULL,
 [status]                   INT NOT NULL,
 isuserlocalizedlabel       BIT NOT NULL,
 localizedlabellanguagecode INT NOT NULL,
 localizedlabel             NVARCHAR(256) NULL,
 PRIMARY KEY CLUSTERED ( entityname, [state], [status], isuserlocalizedlabel, localizedlabellanguagecode)
);

CREATE TABLE dbo.statemetadata
(
 entityname                 NVARCHAR(64) NOT NULL,
 [state]                    INT NOT NULL,
 isuserlocalizedlabel       BIT NOT NULL,
 localizedlabellanguagecode INT NOT NULL,
 localizedlabel             NVARCHAR(256) NULL,
 PRIMARY KEY CLUSTERED ( entityname, [state], isuserlocalizedlabel, localizedlabellanguagecode)
);


CREATE TABLE dbo.globaloptionsetmetadata
(
 optionsetname              NVARCHAR(64) NOT NULL,
 [option]                   INT NOT NULL,
 isuserlocalizedlabel       BIT NOT NULL,
 localizedlabellanguagecode INT NOT NULL,
 localizedlabel             NVARCHAR(256) NULL,
 PRIMARY KEY CLUSTERED ( optionsetname, [option], isuserlocalizedlabel, localizedlabellanguagecode)
);

-- Account
CREATE TABLE [dbo].[account](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[address1_addresstypecode] [int] NULL,
	[msdyn_travelchargetype] [int] NULL,
	[address1_shippingmethodcode] [int] NULL,
	[accountcategorycode] [int] NULL,
	[address1_freighttermscode] [int] NULL,
	[preferredappointmenttimecode] [int] NULL,
	[accountclassificationcode] [int] NULL,
	[customertypecode] [int] NULL,
	[ownershipcode] [int] NULL,
	[territorycode] [int] NULL,
	[industrycode] [int] NULL,
	[businesstypecode] [int] NULL,
	[shippingmethodcode] [int] NULL,
	[paymenttermscode] [int] NULL,
	[accountratingcode] [int] NULL,
	[address2_addresstypecode] [int] NULL,
	[customersizecode] [int] NULL,
	[preferredcontactmethodcode] [int] NULL,
	[address2_shippingmethodcode] [int] NULL,
	[preferredappointmentdaycode] [int] NULL,
	[address2_freighttermscode] [int] NULL,
	[donotpostalmail] [bit] NULL,
	[donotsendmm] [bit] NULL,
	[creditonhold] [bit] NULL,
	[donotbulkpostalmail] [bit] NULL,
	[isprivate] [bit] NULL,
	[donotbulkemail] [bit] NULL,
	[donotfax] [bit] NULL,
	[donotemail] [bit] NULL,
	[donotphone] [bit] NULL,
	[marketingonly] [bit] NULL,
	[merged] [bit] NULL,
	[followemail] [bit] NULL,
	[participatesinworkflow] [bit] NULL,
	[msdyn_taxexempt] [bit] NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[originatingleadid] [uniqueidentifier] NULL,
	[originatingleadid_entitytype] [nvarchar](128) NULL,
	[territoryid] [uniqueidentifier] NULL,
	[territoryid_entitytype] [nvarchar](128) NULL,
	[primarycontactid] [uniqueidentifier] NULL,
	[primarycontactid_entitytype] [nvarchar](128) NULL,
	[parentaccountid] [uniqueidentifier] NULL,
	[parentaccountid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_preferredresource] [uniqueidentifier] NULL,
	[msdyn_preferredresource_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_billingaccount] [uniqueidentifier] NULL,
	[msdyn_billingaccount_entitytype] [nvarchar](128) NULL,
	[createdbyexternalparty] [uniqueidentifier] NULL,
	[createdbyexternalparty_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[preferredequipmentid] [uniqueidentifier] NULL,
	[preferredequipmentid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[masterid] [uniqueidentifier] NULL,
	[masterid_entitytype] [nvarchar](128) NULL,
	[modifiedbyexternalparty] [uniqueidentifier] NULL,
	[modifiedbyexternalparty_entitytype] [nvarchar](128) NULL,
	[defaultpricelevelid] [uniqueidentifier] NULL,
	[defaultpricelevelid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[preferredserviceid] [uniqueidentifier] NULL,
	[preferredserviceid_entitytype] [nvarchar](128) NULL,
	[msdyn_salestaxcode] [uniqueidentifier] NULL,
	[msdyn_salestaxcode_entitytype] [nvarchar](128) NULL,
	[preferredsystemuserid] [uniqueidentifier] NULL,
	[preferredsystemuserid_entitytype] [nvarchar](128) NULL,
	[msdyn_serviceterritory] [uniqueidentifier] NULL,
	[msdyn_serviceterritory_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[aging90] [decimal](38, 2) NULL,
	[openrevenue] [decimal](38, 2) NULL,
	[aging30] [decimal](38, 2) NULL,
	[msdyn_travelcharge_base] [decimal](38, 2) NULL,
	[aging60_base] [decimal](38, 4) NULL,
	[creditlimit] [decimal](38, 2) NULL,
	[openrevenue_base] [decimal](38, 2) NULL,
	[revenue] [decimal](38, 2) NULL,
	[marketcap] [decimal](38, 2) NULL,
	[aging60] [decimal](38, 2) NULL,
	[msdyn_travelcharge] [decimal](38, 2) NULL,
	[creditlimit_base] [decimal](38, 4) NULL,
	[revenue_base] [decimal](38, 4) NULL,
	[aging90_base] [decimal](38, 4) NULL,
	[marketcap_base] [decimal](38, 4) NULL,
	[aging30_base] [decimal](38, 4) NULL,
	[emailaddress3] [nvarchar](100) NULL,
	[emailaddress2] [nvarchar](100) NULL,
	[emailaddress1] [nvarchar](100) NULL,
	[masteraccountidyominame] [nvarchar](100) NULL,
	[address1_city] [nvarchar](80) NULL,
	[address1_longitude] [decimal](38, 5) NULL,
	[modifiedon] [datetime] NULL,
	[overriddencreatedon] [datetime] NULL,
	[websiteurl] [nvarchar](200) NULL,
	[sharesoutstanding] [int] NULL,
	[primarycontactidname] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[msdyn_salestaxcodename] [nvarchar](100) NULL,
	[preferredsystemuseridyominame] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[opendeals_date] [datetime] NULL,
	[modifiedbyexternalpartyyominame] [nvarchar](100) NULL,
	[masteraccountidname] [nvarchar](100) NULL,
	[preferredsystemuseridname] [nvarchar](100) NULL,
	[address2_stateorprovince] [nvarchar](50) NULL,
	[address2_country] [nvarchar](80) NULL,
	[address2_line2] [nvarchar](250) NULL,
	[msdyn_preferredresourcename] [nvarchar](100) NULL,
	[address1_line3] [nvarchar](250) NULL,
	[onholdtime] [int] NULL,
	[parentaccountidname] [nvarchar](100) NULL,
	[originatingleadidname] [nvarchar](100) NULL,
	[address1_utcoffset] [int] NULL,
	[numberofemployees] [int] NULL,
	[modifiedbyexternalpartyname] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[address2_county] [nvarchar](50) NULL,
	[telephone3] [nvarchar](50) NULL,
	[address2_city] [nvarchar](80) NULL,
	[msdyn_taxexemptnumber] [nvarchar](20) NULL,
	[address2_latitude] [decimal](38, 5) NULL,
	[createdon] [datetime] NULL,
	[address2_line1] [nvarchar](250) NULL,
	[address1_composite] [nvarchar](max) NULL,
	[opendeals_state] [int] NULL,
	[address2_postalcode] [nvarchar](20) NULL,
	[lastusedincampaign] [datetime] NULL,
	[processid] [uniqueidentifier] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[address2_line3] [nvarchar](250) NULL,
	[description] [nvarchar](max) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[address1_county] [nvarchar](50) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[address1_line1] [nvarchar](250) NULL,
	[address2_postofficebox] [nvarchar](20) NULL,
	[address2_telephone1] [nvarchar](50) NULL,
	[address2_telephone2] [nvarchar](50) NULL,
	[address2_telephone3] [nvarchar](50) NULL,
	[originatingleadidyominame] [nvarchar](100) NULL,
	[address1_addressid] [uniqueidentifier] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[territoryidname] [nvarchar](100) NULL,
	[yominame] [nvarchar](160) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[address2_name] [nvarchar](200) NULL,
	[openrevenue_state] [int] NULL,
	[primarysatoriid] [nvarchar](200) NULL,
	[name] [nvarchar](160) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[timespentbymeonemailandmeetings] [nvarchar](1250) NULL,
	[primarytwitterid] [nvarchar](20) NULL,
	[owneridname] [nvarchar](100) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[address2_composite] [nvarchar](max) NULL,
	[address1_country] [nvarchar](80) NULL,
	[address1_stateorprovince] [nvarchar](50) NULL,
	[createdbyexternalpartyyominame] [nvarchar](100) NULL,
	[msdyn_billingaccountyominame] [nvarchar](100) NULL,
	[address1_telephone1] [nvarchar](50) NULL,
	[address1_telephone2] [nvarchar](50) NULL,
	[address1_telephone3] [nvarchar](50) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[address1_postofficebox] [nvarchar](20) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[fax] [nvarchar](50) NULL,
	[sic] [nvarchar](20) NULL,
	[address2_utcoffset] [int] NULL,
	[stageid] [uniqueidentifier] NULL,
	[accountnumber] [nvarchar](20) NULL,
	[address2_fax] [nvarchar](50) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[address2_longitude] [decimal](38, 5) NULL,
	[ftpsiteurl] [nvarchar](200) NULL,
	[preferredequipmentidname] [nvarchar](100) NULL,
	[defaultpricelevelidname] [nvarchar](100) NULL,
	[address1_primarycontactname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[address1_line2] [nvarchar](250) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[openrevenue_date] [datetime] NULL,
	[address2_upszone] [nvarchar](4) NULL,
	[address1_postalcode] [nvarchar](20) NULL,
	[tickersymbol] [nvarchar](10) NULL,
	[preferredserviceidname] [nvarchar](100) NULL,
	[createdbyexternalpartyname] [nvarchar](100) NULL,
	[msdyn_serviceterritoryname] [nvarchar](100) NULL,
	[stockexchange] [nvarchar](20) NULL,
	[msdyn_billingaccountname] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[msdyn_workorderinstructions] [nvarchar](max) NULL,
	[telephone2] [nvarchar](50) NULL,
	[versionnumber] [bigint] NULL,
	[accountid] [uniqueidentifier] NULL,
	[telephone1] [nvarchar](50) NULL,
	[address1_name] [nvarchar](200) NULL,
	[address1_fax] [nvarchar](50) NULL,
	[address1_latitude] [decimal](38, 5) NULL,
	[primarycontactidyominame] [nvarchar](100) NULL,
	[new_test] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[address1_upszone] [nvarchar](4) NULL,
	[address2_addressid] [uniqueidentifier] NULL,
	[slaname] [nvarchar](100) NULL,
	[parentaccountidyominame] [nvarchar](100) NULL,
	[address2_primarycontactname] [nvarchar](100) NULL,
	[opendeals] [int] NULL
);

-- appointment
CREATE TABLE [dbo].[appointment](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[instancetypecode] [int] NULL,
	[attachmenterrors] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[ismapiprivate] [bit] NULL,
	[isalldayevent] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[organizer] [uniqueidentifier] NULL,
	[requiredattendees] [uniqueidentifier] NULL,
	[optionalattendees] [uniqueidentifier] NULL,
	[createdon] [datetime] NULL,
	[originalstartdate] [datetime] NULL,
	[attachmentcount] [int] NULL,
	[activityid] [uniqueidentifier] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[onholdtime] [int] NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[scheduledstart] [datetime] NULL,
	[actualstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subcategory] [nvarchar](250) NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[overriddencreatedon] [datetime] NULL,
	[seriesid] [uniqueidentifier] NULL,
	[subject] [nvarchar](200) NULL,
	[versionnumber] [bigint] NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[scheduleddurationminutes] [int] NULL,
	[processid] [uniqueidentifier] NULL,
	[description] [nvarchar](max) NULL,
	[modifiedon] [datetime] NULL,
	[location] [nvarchar](200) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[globalobjectid] [nvarchar](300) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[sortdate] [datetime] NULL,
	[lastonholdtime] [datetime] NULL,
	[stageid] [uniqueidentifier] NULL,
	[scheduledend] [datetime] NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[slaname] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[modifiedfieldsmask] [nvarchar](max) NULL,
	[outlookownerapptid] [int] NULL,
	[category] [nvarchar](250) NULL
);

-- contact

CREATE TABLE [dbo].[contact](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[address3_addresstypecode] [int] NULL,
	[address1_addresstypecode] [int] NULL,
	[address1_freighttermscode] [int] NULL,
	[accountrolecode] [int] NULL,
	[address1_shippingmethodcode] [int] NULL,
	[gendercode] [int] NULL,
	[preferredappointmenttimecode] [int] NULL,
	[customertypecode] [int] NULL,
	[customersizecode] [int] NULL,
	[preferredcontactmethodcode] [int] NULL,
	[address2_freighttermscode] [int] NULL,
	[educationcode] [int] NULL,
	[address3_freighttermscode] [int] NULL,
	[address3_shippingmethodcode] [int] NULL,
	[paymenttermscode] [int] NULL,
	[address2_addresstypecode] [int] NULL,
	[preferredappointmentdaycode] [int] NULL,
	[haschildrencode] [int] NULL,
	[familystatuscode] [int] NULL,
	[address2_shippingmethodcode] [int] NULL,
	[leadsourcecode] [int] NULL,
	[shippingmethodcode] [int] NULL,
	[territorycode] [int] NULL,
	[donotpostalmail] [bit] NULL,
	[donotsendmm] [bit] NULL,
	[creditonhold] [bit] NULL,
	[donotbulkpostalmail] [bit] NULL,
	[isprivate] [bit] NULL,
	[donotbulkemail] [bit] NULL,
	[donotfax] [bit] NULL,
	[isautocreate] [bit] NULL,
	[donotemail] [bit] NULL,
	[marketingonly] [bit] NULL,
	[isbackofficecustomer] [bit] NULL,
	[participatesinworkflow] [bit] NULL,
	[merged] [bit] NULL,
	[donotphone] [bit] NULL,
	[followemail] [bit] NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[originatingleadid] [uniqueidentifier] NULL,
	[originatingleadid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[parentcontactid] [uniqueidentifier] NULL,
	[parentcontactid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[preferredequipmentid] [uniqueidentifier] NULL,
	[preferredequipmentid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[masterid] [uniqueidentifier] NULL,
	[masterid_entitytype] [nvarchar](128) NULL,
	[modifiedbyexternalparty] [uniqueidentifier] NULL,
	[modifiedbyexternalparty_entitytype] [nvarchar](128) NULL,
	[defaultpricelevelid] [uniqueidentifier] NULL,
	[defaultpricelevelid_entitytype] [nvarchar](128) NULL,
	[accountid] [uniqueidentifier] NULL,
	[accountid_entitytype] [nvarchar](128) NULL,
	[createdbyexternalparty] [uniqueidentifier] NULL,
	[createdbyexternalparty_entitytype] [nvarchar](128) NULL,
	[preferredserviceid] [uniqueidentifier] NULL,
	[preferredserviceid_entitytype] [nvarchar](128) NULL,
	[preferredsystemuserid] [uniqueidentifier] NULL,
	[preferredsystemuserid_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[parentcustomerid] [uniqueidentifier] NULL,
	[parentcustomerid_entitytype] [nvarchar](128) NULL,
	[aging90] [decimal](38, 2) NULL,
	[aging30] [decimal](38, 2) NULL,
	[aging60_base] [decimal](38, 4) NULL,
	[creditlimit] [decimal](38, 2) NULL,
	[annualincome_base] [decimal](38, 4) NULL,
	[aging90_base] [decimal](38, 4) NULL,
	[annualincome] [decimal](38, 2) NULL,
	[aging60] [decimal](38, 2) NULL,
	[creditlimit_base] [decimal](38, 4) NULL,
	[aging30_base] [decimal](38, 4) NULL,
	[emailaddress2] [nvarchar](100) NULL,
	[emailaddress1] [nvarchar](100) NULL,
	[address1_city] [nvarchar](80) NULL,
	[address3_line1] [nvarchar](250) NULL,
	[address1_line1] [nvarchar](250) NULL,
	[address1_longitude] [decimal](38, 5) NULL,
	[modifiedon] [datetime] NULL,
	[overriddencreatedon] [datetime] NULL,
	[yomilastname] [nvarchar](150) NULL,
	[yomifirstname] [nvarchar](150) NULL,
	[yomifullname] [nvarchar](450) NULL,
	[createdbyexternalpartyname] [nvarchar](100) NULL,
	[address3_line2] [nvarchar](250) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[address3_telephone1] [nvarchar](50) NULL,
	[address3_line3] [nvarchar](250) NULL,
	[address2_county] [nvarchar](50) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[preferredsystemuseridyominame] [nvarchar](100) NULL,
	[address3_utcoffset] [int] NULL,
	[externaluseridentifier] [nvarchar](50) NULL,
	[address3_primarycontactname] [nvarchar](100) NULL,
	[modifiedbyexternalpartyyominame] [nvarchar](100) NULL,
	[preferredsystemuseridname] [nvarchar](100) NULL,
	[preferredserviceidname] [nvarchar](100) NULL,
	[address2_stateorprovince] [nvarchar](50) NULL,
	[mobilephone] [nvarchar](50) NULL,
	[parentcustomeridyominame] [nvarchar](450) NULL,
	[address2_country] [nvarchar](80) NULL,
	[address2_line2] [nvarchar](250) NULL,
	[address3_stateorprovince] [nvarchar](50) NULL,
	[assistantphone] [nvarchar](50) NULL,
	[onholdtime] [int] NULL,
	[parentcontactidyominame] [nvarchar](100) NULL,
	[address3_longitude] [decimal](38, 5) NULL,
	[birthdate] [datetime] NULL,
	[originatingleadidname] [nvarchar](100) NULL,
	[address1_utcoffset] [int] NULL,
	[managerphone] [nvarchar](50) NULL,
	[employeeid] [nvarchar](50) NULL,
	[versionnumber] [bigint] NULL,
	[modifiedbyexternalpartyname] [nvarchar](100) NULL,
	[address3_upszone] [nvarchar](4) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[address3_composite] [nvarchar](max) NULL,
	[telephone3] [nvarchar](50) NULL,
	[childrensnames] [nvarchar](255) NULL,
	[address2_latitude] [decimal](38, 5) NULL,
	[createdon] [datetime] NULL,
	[slaname] [nvarchar](100) NULL,
	[address1_composite] [nvarchar](max) NULL,
	[firstname] [nvarchar](50) NULL,
	[callback] [nvarchar](50) NULL,
	[address2_postalcode] [nvarchar](20) NULL,
	[lastusedincampaign] [datetime] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[processid] [uniqueidentifier] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[governmentid] [nvarchar](50) NULL,
	[address2_line3] [nvarchar](250) NULL,
	[description] [nvarchar](max) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[spousesname] [nvarchar](100) NULL,
	[address1_county] [nvarchar](50) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[address3_county] [nvarchar](50) NULL,
	[pager] [nvarchar](50) NULL,
	[address2_postofficebox] [nvarchar](20) NULL,
	[address2_telephone1] [nvarchar](50) NULL,
	[address2_telephone2] [nvarchar](50) NULL,
	[address2_telephone3] [nvarchar](50) NULL,
	[originatingleadidyominame] [nvarchar](100) NULL,
	[telephone1] [nvarchar](50) NULL,
	[address1_addressid] [uniqueidentifier] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[websiteurl] [nvarchar](200) NULL,
	[address2_name] [nvarchar](100) NULL,
	[middlename] [nvarchar](50) NULL,
	[address3_telephone2] [nvarchar](50) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[timespentbymeonemailandmeetings] [nvarchar](1250) NULL,
	[parentcustomeridname] [nvarchar](160) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[owneridname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[address2_composite] [nvarchar](max) NULL,
	[address1_country] [nvarchar](80) NULL,
	[address1_stateorprovince] [nvarchar](50) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[address1_line3] [nvarchar](250) NULL,
	[createdbyexternalpartyyominame] [nvarchar](100) NULL,
	[mastercontactidname] [nvarchar](100) NULL,
	[jobtitle] [nvarchar](100) NULL,
	[nickname] [nvarchar](50) NULL,
	[managername] [nvarchar](100) NULL,
	[address1_telephone1] [nvarchar](50) NULL,
	[address1_telephone2] [nvarchar](50) NULL,
	[address1_telephone3] [nvarchar](50) NULL,
	[contactid] [uniqueidentifier] NULL,
	[address2_utcoffset] [int] NULL,
	[suffix] [nvarchar](10) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[fax] [nvarchar](50) NULL,
	[mastercontactidyominame] [nvarchar](100) NULL,
	[assistantname] [nvarchar](100) NULL,
	[yomimiddlename] [nvarchar](150) NULL,
	[address3_country] [nvarchar](80) NULL,
	[address2_fax] [nvarchar](50) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[address2_longitude] [decimal](38, 5) NULL,
	[preferredequipmentidname] [nvarchar](100) NULL,
	[address3_latitude] [decimal](38, 5) NULL,
	[accountidname] [nvarchar](100) NULL,
	[address1_primarycontactname] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[address1_line2] [nvarchar](250) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[company] [nvarchar](50) NULL,
	[address2_upszone] [nvarchar](4) NULL,
	[address3_name] [nvarchar](200) NULL,
	[address3_fax] [nvarchar](50) NULL,
	[salutation] [nvarchar](100) NULL,
	[address1_postalcode] [nvarchar](20) NULL,
	[stageid] [uniqueidentifier] NULL,
	[address3_telephone3] [nvarchar](50) NULL,
	[address3_postalcode] [nvarchar](20) NULL,
	[defaultpricelevelidname] [nvarchar](100) NULL,
	[address2_addressid] [uniqueidentifier] NULL,
	[home2] [nvarchar](50) NULL,
	[anniversary] [datetime] NULL,
	[importsequencenumber] [int] NULL,
	[address2_city] [nvarchar](80) NULL,
	[telephone2] [nvarchar](50) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[department] [nvarchar](100) NULL,
	[address3_city] [nvarchar](80) NULL,
	[business2] [nvarchar](50) NULL,
	[address1_name] [nvarchar](200) NULL,
	[address1_fax] [nvarchar](50) NULL,
	[address1_latitude] [decimal](38, 5) NULL,
	[emailaddress3] [nvarchar](100) NULL,
	[address3_postofficebox] [nvarchar](20) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[parentcustomeridtype] [nvarchar](4000) NULL,
	[parentcontactidname] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[address2_line1] [nvarchar](250) NULL,
	[address1_upszone] [nvarchar](4) NULL,
	[lastname] [nvarchar](50) NULL,
	[accountidyominame] [nvarchar](100) NULL,
	[ftpsiteurl] [nvarchar](200) NULL,
	[numberofchildren] [int] NULL,
	[address1_postofficebox] [nvarchar](20) NULL,
	[address2_primarycontactname] [nvarchar](100) NULL,
	[fullname] [nvarchar](160) NULL,
	[address3_addressid] [uniqueidentifier]
);

-- email

CREATE TABLE [dbo].[email](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[notifications] [int] NULL,
	[emailreminderstatus] [int] NULL,
	[emailremindertype] [int] NULL,
	[deliveryprioritycode] [int] NULL,
	[prioritycode] [int] NULL,
	[correlationmethod] [int] NULL,
	[isworkflowcreated] [bit] NULL,
	[readreceiptrequested] [bit] NULL,
	[isbilled] [bit] NULL,
	[isemailfollowed] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[deliveryreceiptrequested] [bit] NULL,
	[compressed] [bit] NULL,
	[followemailuserpreference] [bit] NULL,
	[directioncode] [bit] NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[parentactivityid] [uniqueidentifier] NULL,
	[parentactivityid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[emailsender] [uniqueidentifier] NULL,
	[emailsender_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[sendersaccount] [uniqueidentifier] NULL,
	[sendersaccount_entitytype] [nvarchar](128) NULL,
	[sendermailboxid] [uniqueidentifier] NULL,
	[sendermailboxid_entitytype] [nvarchar](128) NULL,
	[templateid] [uniqueidentifier] NULL,
	[templateid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[to] [uniqueidentifier] NULL,
	[bcc] [uniqueidentifier] NULL,
	[from] [uniqueidentifier] NULL,
	[cc] [uniqueidentifier] NULL,
	[scheduledend] [datetime] NULL,
	[emailsendername] [nvarchar](400) NULL,
	[modifiedon] [datetime] NULL,
	[overriddencreatedon] [datetime] NULL,
	[senton] [datetime] NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[parentactivityidname] [nvarchar](400) NULL,
	[sendersaccountobjecttypecode] [nvarchar](4000) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[delayedemailsendtime] [datetime] NULL,
	[activityid] [uniqueidentifier] NULL,
	[submittedby] [nvarchar](250) NULL,
	[linksclickedcount] [int] NULL,
	[emailsenderyominame] [nvarchar](400) NULL,
	[trackingtoken] [nvarchar](50) NULL,
	[onholdtime] [int] NULL,
	[lastopenedtime] [datetime] NULL,
	[attachmentcount] [int] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[baseconversationindexhash] [int] NULL,
	[conversationtrackingid] [uniqueidentifier] NULL,
	[messageiddupcheck] [uniqueidentifier] NULL,
	[createdon] [datetime] NULL,
	[category] [nvarchar](250) NULL,
	[replycount] [int] NULL,
	[actualstart] [datetime] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[description] [nvarchar](max) NULL,
	[sender] [nvarchar](250) NULL,
	[sendersaccountyominame] [nvarchar](400) NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[sortdate] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[opencount] [int] NULL,
	[safedescription] [nvarchar](max) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[reminderactioncardid] [uniqueidentifier] NULL,
	[isunsafe] [int] NULL,
	[sendersaccountname] [nvarchar](400) NULL,
	[owneridname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[processid] [uniqueidentifier] NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[postponeemailprocessinguntil] [datetime] NULL,
	[emailreminderexpirytime] [datetime] NULL,
	[emailremindertext] [nvarchar](1250) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[sendermailboxidname] [nvarchar](100) NULL,
	[inreplyto] [nvarchar](320) NULL,
	[subject] [nvarchar](200) NULL,
	[conversationindex] [nvarchar](2048) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[emailtrackingid] [uniqueidentifier] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[emailsenderobjecttypecode] [nvarchar](4000) NULL,
	[actualdurationminutes] [int] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[subcategory] [nvarchar](250) NULL,
	[templateidname] [nvarchar](100) NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[messageid] [nvarchar](320) NULL,
	[stageid] [uniqueidentifier] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[scheduleddurationminutes] [int] NULL,
	[attachmentopencount] [int] NULL,
	[importsequencenumber] [int] NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[deliveryattempts] [int] NULL,
	[torecipients] [nvarchar](500) NULL,
	[versionnumber] [bigint] NULL,
	[mimetype] [nvarchar](256) NULL,
	[scheduledstart] [datetime] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[slaname] [nvarchar](100) NULL
);


--fax
CREATE TABLE [dbo].[fax](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[directioncode] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[from] [uniqueidentifier] NULL,
	[to] [uniqueidentifier] NULL,
	[actualstart] [datetime] NULL,
	[versionnumber] [bigint] NULL,
	[billingcode] [nvarchar](50) NULL,
	[activityid] [uniqueidentifier] NULL,
	[createdon] [datetime] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[onholdtime] [int] NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[scheduledstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subcategory] [nvarchar](250) NULL,
	[subject] [nvarchar](200) NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[actualdurationminutes] [int] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[scheduleddurationminutes] [int] NULL,
	[processid] [uniqueidentifier] NULL,
	[sortdate] [datetime] NULL,
	[description] [nvarchar](max) NULL,
	[modifiedon] [datetime] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[coverpagename] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[stageid] [uniqueidentifier] NULL,
	[scheduledend] [datetime] NULL,
	[faxnumber] [nvarchar](200) NULL,
	[numberofpages] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[slaname] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[category] [nvarchar](250) NULL,
	[tsid] [nvarchar](20) NULL
);


-- incident (used for case)

CREATE TABLE [dbo].[incident](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[caseorigincode] [int] NULL,
	[customersatisfactioncode] [int] NULL,
	[firstresponseslastatus] [int] NULL,
	[servicestage] [int] NULL,
	[contractservicelevelcode] [int] NULL,
	[casetypecode] [int] NULL,
	[severitycode] [int] NULL,
	[resolvebyslastatus] [int] NULL,
	[incidentstagecode] [int] NULL,
	[prioritycode] [int] NULL,
	[messagetypecode] [int] NULL,
	[activitiescomplete] [bit] NULL,
	[blockedprofile] [bit] NULL,
	[firstresponsesent] [bit] NULL,
	[isescalated] [bit] NULL,
	[checkemail] [bit] NULL,
	[decremententitlementterm] [bit] NULL,
	[routecase] [bit] NULL,
	[merged] [bit] NULL,
	[isdecrementing] [bit] NULL,
	[customercontacted] [bit] NULL,
	[followuptaskcreated] [bit] NULL,
	[contactid] [uniqueidentifier] NULL,
	[contactid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[resolvebykpiid] [uniqueidentifier] NULL,
	[resolvebykpiid_entitytype] [nvarchar](128) NULL,
	[productid] [uniqueidentifier] NULL,
	[productid_entitytype] [nvarchar](128) NULL,
	[existingcase] [uniqueidentifier] NULL,
	[existingcase_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[contractid] [uniqueidentifier] NULL,
	[contractid_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[responsiblecontactid] [uniqueidentifier] NULL,
	[responsiblecontactid_entitytype] [nvarchar](128) NULL,
	[accountid] [uniqueidentifier] NULL,
	[accountid_entitytype] [nvarchar](128) NULL,
	[kbarticleid] [uniqueidentifier] NULL,
	[kbarticleid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[parentcaseid] [uniqueidentifier] NULL,
	[parentcaseid_entitytype] [nvarchar](128) NULL,
	[primarycontactid] [uniqueidentifier] NULL,
	[primarycontactid_entitytype] [nvarchar](128) NULL,
	[msdyn_incidenttype] [uniqueidentifier] NULL,
	[msdyn_incidenttype_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[subjectid] [uniqueidentifier] NULL,
	[subjectid_entitytype] [nvarchar](128) NULL,
	[entitlementid] [uniqueidentifier] NULL,
	[entitlementid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[masterid] [uniqueidentifier] NULL,
	[masterid_entitytype] [nvarchar](128) NULL,
	[modifiedbyexternalparty] [uniqueidentifier] NULL,
	[modifiedbyexternalparty_entitytype] [nvarchar](128) NULL,
	[firstresponsebykpiid] [uniqueidentifier] NULL,
	[firstresponsebykpiid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[createdbyexternalparty] [uniqueidentifier] NULL,
	[createdbyexternalparty_entitytype] [nvarchar](128) NULL,
	[contractdetailid] [uniqueidentifier] NULL,
	[contractdetailid_entitytype] [nvarchar](128) NULL,
	[socialprofileid] [uniqueidentifier] NULL,
	[socialprofileid_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[customerid] [uniqueidentifier] NULL,
	[customerid_entitytype] [nvarchar](128) NULL,
	[ticketnumber] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[primarycontactidyominame] [nvarchar](100) NULL,
	[createdbyexternalpartyname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[entityimage_timestamp] [bigint] NULL,
	[contactidname] [nvarchar](100) NULL,
	[responsiblecontactidyominame] [nvarchar](100) NULL,
	[customeridyominame] [nvarchar](450) NULL,
	[primarycontactidname] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[msdyn_incidenttypename] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[modifiedbyexternalpartyyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[sentimentvalue] [decimal](38, 2) NULL,
	[onholdtime] [int] NULL,
	[socialprofileidname] [nvarchar](100) NULL,
	[responsiblecontactidname] [nvarchar](100) NULL,
	[contractdetailidname] [nvarchar](100) NULL,
	[contactidyominame] [nvarchar](100) NULL,
	[modifiedbyexternalpartyname] [nvarchar](100) NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[influencescore] [decimal](38, 2) NULL,
	[title] [nvarchar](200) NULL,
	[createdon] [datetime] NULL,
	[productidname] [nvarchar](100) NULL,
	[customeridtype] [nvarchar](4000) NULL,
	[processid] [uniqueidentifier] NULL,
	[productserialnumber] [nvarchar](100) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[description] [nvarchar](max) NULL,
	[actualserviceunits] [int] NULL,
	[accountidname] [nvarchar](100) NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[billedserviceunits] [int] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[responseby] [datetime] NULL,
	[createdbyexternalpartyyominame] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[accountidyominame] [nvarchar](100) NULL,
	[subjectidname] [nvarchar](100) NULL,
	[followupby] [datetime] NULL,
	[contractidname] [nvarchar](100) NULL,
	[lastonholdtime] [datetime] NULL,
	[masteridname] [nvarchar](100) NULL,
	[kbarticleidname] [nvarchar](100) NULL,
	[stageid] [uniqueidentifier] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[customeridname] [nvarchar](160) NULL,
	[importsequencenumber] [int] NULL,
	[incidentid] [uniqueidentifier] NULL,
	[entitlementidname] [nvarchar](100) NULL,
	[firstresponsebykpiidname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[resolveby] [datetime] NULL,
	[resolvebykpiidname] [nvarchar](100) NULL,
	[parentcaseidname] [nvarchar](100) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[escalatedon] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[slaname] [nvarchar](100) NULL,
	[numberofchildincidents] [int] NULL
);



-- letter

CREATE TABLE [dbo].[letter](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[directioncode] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[from] [uniqueidentifier] NULL,
	[to] [uniqueidentifier] NULL,
	[bcc] [uniqueidentifier] NULL,
	[cc] [uniqueidentifier] NULL,
	[versionnumber] [bigint] NULL,
	[timezoneruleversionnumber] [int] NULL,
	[createdon] [datetime] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[scheduledstart] [datetime] NULL,
	[actualstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subject] [nvarchar](200) NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[scheduleddurationminutes] [int] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[subcategory] [nvarchar](250) NULL,
	[category] [nvarchar](250) NULL,
	[processid] [uniqueidentifier] NULL,
	[description] [nvarchar](max) NULL,
	[modifiedon] [datetime] NULL,
	[createdbyname] [nvarchar](100) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[sortdate] [datetime] NULL,
	[lastonholdtime] [datetime] NULL,
	[stageid] [uniqueidentifier] NULL,
	[address] [nvarchar](200) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[activityid] [uniqueidentifier] NULL,
	[onholdtime] [int] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[scheduledend] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL,
	[slaname] [nvarchar](100) NULL
);


-- msdyn_survey
CREATE TABLE [dbo].[msdyn_survey](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_respondentdataactiontype] [int] NULL,
	[msdyn_automaticallysendemailresponse] [int] NULL,
	[msdyn_calculatescore] [int] NULL,
	[msdyn_addtositemap] [int] NULL,
	[msdyn_feedbackgenerationstatus] [int] NULL,
	[msdyn_generatefeedback] [int] NULL,
	[msdyn_usecaptcha] [int] NULL,
	[msdyn_unsubscribe] [int] NULL,
	[msdyn_createalert] [int] NULL,
	[msdyn_assignresponses] [int] NULL,
	[msdyn_convertresponsestofeedback] [int] NULL,
	[msdyn_userulesengine] [bit] NULL,
	[msdyn_generatesurveymanualnow] [bit] NULL,
	[msdyn_enablesocialsharing] [bit] NULL,
	[msdyn_allowsave] [bit] NULL,
	[msdyn_relatetoaccount] [bit] NULL,
	[msdyn_generatesurveyresponses] [bit] NULL,
	[msdyn_donotbulkemail] [bit] NULL,
	[msdyn_showtechnicalhelp] [bit] NULL,
	[msdyn_restrictmultiplecompletions] [bit] NULL,
	[msdyn_showprogressbar] [bit] NULL,
	[msdyn_acceptanonymousresponses] [bit] NULL,
	[msdyn_showentityinnavigationpane] [bit] NULL,
	[msdyn_useversioning] [bit] NULL,
	[msdyn_unsubscriberesponses] [bit] NULL,
	[msdyn_pagenumbers] [bit] NULL,
	[msdyn_donotemail] [bit] NULL,
	[msdyn_closeinvitationonresponsereceived] [bit] NULL,
	[msdyn_createleadforanonymousresponses] [bit] NULL,
	[msdyn_relatetocontact] [bit] NULL,
	[msdyn_runiniframe] [bit] NULL,
	[msdyn_donotfax] [bit] NULL,
	[msdyn_generateform] [bit] NULL,
	[msdyn_generatedashboard] [bit] NULL,
	[msdyn_donotsendmm] [bit] NULL,
	[msdyn_surveyimageid] [uniqueidentifier] NULL,
	[msdyn_surveyimageid_entitytype] [nvarchar](128) NULL,
	[msdyn_keymeasuremapping] [uniqueidentifier] NULL,
	[msdyn_keymeasuremapping_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_keymeasurequestion] [uniqueidentifier] NULL,
	[msdyn_keymeasurequestion_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_themeid] [uniqueidentifier] NULL,
	[msdyn_themeid_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_configurationid] [uniqueidentifier] NULL,
	[msdyn_configurationid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[msdyn_unsubscribesurvey] [uniqueidentifier] NULL,
	[msdyn_unsubscribesurvey_entitytype] [nvarchar](128) NULL,
	[msdyn_publishinguser] [uniqueidentifier] NULL,
	[msdyn_publishinguser_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_surveyemailaddresstext] [nvarchar](100) NULL,
	[msdyn_abbreviation] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_surveyheadertextblock] [nvarchar](max) NULL,
	[msdyn_translationtrigger] [datetime] NULL,
	[msdyn_language] [int] NULL,
	[msdyn_relatedentity] [nvarchar](100) NULL,
	[msdyn_publishwarnings] [nvarchar](max) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[msdyn_lastgeneratedon] [datetime] NULL,
	[msdyn_entitygenerationtrigger] [datetime] NULL,
	[msdyn_runtimetitle] [nvarchar](100) NULL,
	[msdyn_description] [nvarchar](500) NULL,
	[msdyn_invitationsnippet] [nvarchar](512) NULL,
	[msdyn_keymeasure] [nvarchar](100) NULL,
	[msdyn_publishinguseryominame] [nvarchar](100) NULL,
	[msdyn_configurationidname] [nvarchar](100) NULL,
	[msdyn_themeidname] [nvarchar](100) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[msdyn_alertlowertarget] [decimal](38, 2) NULL,
	[msdyn_uniqueurldescription] [nvarchar](50) NULL,
	[msdyn_translations] [nvarchar](max) NULL,
	[msdyn_pluginexception] [nvarchar](max) NULL,
	[msdyn_publishentitytrigger] [datetime] NULL,
	[msdyn_anonymoussurveyurl] [nvarchar](512) NULL,
	[msdyn_surveycompletelinkurl] [nvarchar](100) NULL,
	[msdyn_surveyurl] [nvarchar](1024) NULL,
	[msdyn_attributegenerationtrigger] [datetime] NULL,
	[msdyn_customlinkurl] [nvarchar](500) NULL,
	[createdon] [datetime] NULL,
	[msdyn_schemaname] [nvarchar](100) NULL,
	[msdyn_publishingusername] [nvarchar](100) NULL,
	[msdyn_submittext] [nvarchar](50) NULL,
	[msdyn_surveyalreadytakentextblock] [nvarchar](max) NULL,
	[msdyn_closeddate] [datetime] NULL,
	[msdyn_unsubscribelinktext] [nvarchar](100) NULL,
	[msdyn_redirectlinktext] [nvarchar](100) NULL,
	[msdyn_versioncode] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_switchtodefaultform] [datetime] NULL,
	[msdyn_unsubscribesurveyname] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[msdyn_previoustext] [nvarchar](50) NULL,
	[msdyn_queuepoptrigger] [datetime] NULL,
	[msdyn_keymeasuremappingname] [nvarchar](100) NULL,
	[emailaddress] [nvarchar](100) NULL,
	[msdyn_relationshipgenerationtrigger] [datetime] NULL,
	[msdyn_emailtemplateid] [nvarchar](200) NULL,
	[msdyn_version] [nvarchar](100) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[msdyn_summaryhtml] [nvarchar](max) NULL,
	[msdyn_solutionname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_surveyid] [uniqueidentifier] NULL,
	[msdyn_savesurveytext] [nvarchar](100) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_keymeasurequestionname] [nvarchar](100) NULL,
	[msdyn_support] [nvarchar](100) NULL,
	[msdyn_pluginignore] [nvarchar](100) NULL,
	[msdyn_stoppeddate] [datetime] NULL,
	[msdyn_customlinkdisplayname] [nvarchar](100) NULL,
	[msdyn_publisheddate] [datetime] NULL,
	[msdyn_previewtrigger] [nvarchar](1024) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[msdyn_currentpage] [int] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[msdyn_cloneddate] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_invitationlinktext] [nvarchar](200) NULL,
	[msdyn_surveycompletetext] [nvarchar](max) NULL,
	[msdyn_queuegenerationdate] [datetime] NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_unsubscribesurveyurl] [nvarchar](100) NULL,
	[msdyn_surveyemailaddress] [nvarchar](100) NULL,
	[msdyn_nexttext] [nvarchar](50) NULL,
	[importsequencenumber] [int] NULL,
	[msdyn_privacypolicylinktext] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[msdyn_responsecount] [int] NULL,
	[msdyn_pluralname] [nvarchar](100) NULL,
	[msdyn_privacypolicyurl] [nvarchar](500) NULL,
	[msdyn_surveyimageidname] [nvarchar](100) NULL,
	[msdyn_formsandviewstrigger] [datetime] NULL,
	[msdyn_redirecturl] [nvarchar](255) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[msdyn_name] [nvarchar](50) NULL,
	[msdyn_languages] [nvarchar](500) NULL,
	[msdyn_feedbackcurrentsteptimestamp] [datetime] NULL,
	[msdyn_feedbackname] [nvarchar](100) NULL,
	[msdyn_iframeurl] [nvarchar](max) NULL
)

-- msdyn_surveyresponse

CREATE TABLE [dbo].[msdyn_surveyresponse](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[msdyn_faceexpressiontype] [int] NULL,
	[msdyn_facialexpression] [int] NULL,
	[msdyn_npstype] [int] NULL,
	[msdyn_facemodel] [int] NULL,
	[msdyn_processingcompletetrigger] [bit] NULL,
	[msdyn_sharedtolinkedin] [bit] NULL,
	[msdyn_sharedtotwitter] [bit] NULL,
	[msdyn_alerttriggered] [bit] NULL,
	[msdyn_sharedtogoogle] [bit] NULL,
	[msdyn_sharedtoyammer] [bit] NULL,
	[msdyn_sharedtofacebook] [bit] NULL,
	[msdyn_campaignresponsetrigger] [bit] NULL,
	[msdyn_linkedanswer14] [uniqueidentifier] NULL,
	[msdyn_linkedanswer14_entitytype] [nvarchar](128) NULL,
	[msdyn_contact] [uniqueidentifier] NULL,
	[msdyn_contact_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer12] [uniqueidentifier] NULL,
	[msdyn_linkedanswer12_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer11] [uniqueidentifier] NULL,
	[msdyn_linkedanswer11_entitytype] [nvarchar](128) NULL,
	[msdyn_case] [uniqueidentifier] NULL,
	[msdyn_case_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer10] [uniqueidentifier] NULL,
	[msdyn_linkedanswer10_entitytype] [nvarchar](128) NULL,
	[msdyn_surveyid] [uniqueidentifier] NULL,
	[msdyn_surveyid_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer6] [uniqueidentifier] NULL,
	[msdyn_linkedanswer6_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer9] [uniqueidentifier] NULL,
	[msdyn_linkedanswer9_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer8] [uniqueidentifier] NULL,
	[msdyn_linkedanswer8_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer5] [uniqueidentifier] NULL,
	[msdyn_linkedanswer5_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer4] [uniqueidentifier] NULL,
	[msdyn_linkedanswer4_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer7] [uniqueidentifier] NULL,
	[msdyn_linkedanswer7_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer1] [uniqueidentifier] NULL,
	[msdyn_linkedanswer1_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer3] [uniqueidentifier] NULL,
	[msdyn_linkedanswer3_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer2] [uniqueidentifier] NULL,
	[msdyn_linkedanswer2_entitytype] [nvarchar](128) NULL,
	[msdyn_surveyinviteid] [uniqueidentifier] NULL,
	[msdyn_surveyinviteid_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer13] [uniqueidentifier] NULL,
	[msdyn_linkedanswer13_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[msdyn_leadid] [uniqueidentifier] NULL,
	[msdyn_leadid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[msdyn_user] [uniqueidentifier] NULL,
	[msdyn_user_entitytype] [nvarchar](128) NULL,
	[msdyn_linkedanswer15] [uniqueidentifier] NULL,
	[msdyn_linkedanswer15_entitytype] [nvarchar](128) NULL,
	[msdyn_account] [uniqueidentifier] NULL,
	[msdyn_account_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[msdyn_customdate2] [datetime] NULL,
	[msdyn_contactyominame] [nvarchar](100) NULL,
	[msdyn_linkedanswer9name] [nvarchar](100) NULL,
	[msdyn_startprocessing] [datetime] NULL,
	[msdyn_linkedanswer11name] [nvarchar](100) NULL,
	[msdyn_leadidname] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[overriddencreatedon] [datetime] NULL,
	[msdyn_language] [nvarchar](6) NULL,
	[msdyn_scoreaspercentage] [decimal](38, 4) NULL,
	[msdyn_linkedanswer3name] [nvarchar](100) NULL,
	[msdyn_maxscore] [decimal](38, 4) NULL,
	[msdyn_satisfactionrating1asint] [int] NULL,
	[msdyn_satisfactionrating1] [decimal](38, 2) NULL,
	[msdyn_version] [nvarchar](100) NULL,
	[msdyn_linkedanswer5name] [nvarchar](100) NULL,
	[msdyn_unsubscribetrigger] [datetime] NULL,
	[msdyn_customnumber20] [decimal](38, 2) NULL,
	[msdyn_leadidyominame] [nvarchar](100) NULL,
	[msdyn_emailresponse] [nvarchar](max) NULL,
	[msdyn_customnumber15] [decimal](38, 2) NULL,
	[msdyn_cityresponse] [nvarchar](max) NULL,
	[msdyn_lastnameresponse] [nvarchar](max) NULL,
	[msdyn_customnumber16] [decimal](38, 2) NULL,
	[msdyn_fax] [nvarchar](max) NULL,
	[msdyn_respondent] [nvarchar](100) NULL,
	[msdyn_surveyidname] [nvarchar](100) NULL,
	[msdyn_countryresponse] [nvarchar](max) NULL,
	[msdyn_linkedanswer12name] [nvarchar](100) NULL,
	[msdyn_contactname] [nvarchar](100) NULL,
	[msdyn_linkedanswer10name] [nvarchar](100) NULL,
	[msdyn_salutationresponse] [nvarchar](max) NULL,
	[createdon] [datetime] NULL,
	[msdyn_accountname] [nvarchar](100) NULL,
	[msdyn_customnumber19] [decimal](38, 2) NULL,
	[msdyn_companyresponse] [nvarchar](max) NULL,
	[msdyn_linkedanswer13name] [nvarchar](100) NULL,
	[msdyn_linkedanswer8name] [nvarchar](100) NULL,
	[msdyn_customnumber13] [decimal](38, 2) NULL,
	[msdyn_responseasjson] [nvarchar](max) NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[msdyn_street2response] [nvarchar](max) NULL,
	[msdyn_versioncode] [nvarchar](100) NULL,
	[msdyn_street1response] [nvarchar](max) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[msdyn_customnumber14] [decimal](38, 2) NULL,
	[msdyn_customvalue3] [nvarchar](max) NULL,
	[msdyn_npscomment] [nvarchar](max) NULL,
	[msdyn_useryominame] [nvarchar](100) NULL,
	[msdyn_responserulestrigger] [datetime] NULL,
	[msdyn_linkedanswer4name] [nvarchar](100) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_casename] [nvarchar](100) NULL,
	[msdyn_createleadtrigger] [datetime] NULL,
	[msdyn_token] [int] NULL,
	[msdyn_customnumber10] [decimal](38, 2) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[msdyn_responsesashtml] [nvarchar](max) NULL,
	[msdyn_score] [decimal](38, 4) NULL,
	[owneridname] [nvarchar](100) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[msdyn_file] [nvarchar](1024) NULL,
	[msdyn_surveyinviteidname] [nvarchar](100) NULL,
	[msdyn_stateresponse] [nvarchar](max) NULL,
	[msdyn_customnumber18] [decimal](38, 2) NULL,
	[msdyn_locale] [nvarchar](6) NULL,
	[emailaddress] [nvarchar](100) NULL,
	[msdyn_createalerttrigger] [datetime] NULL,
	[msdyn_customvalue1] [nvarchar](max) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_responseid] [int] NULL,
	[msdyn_customnumber17] [decimal](38, 2) NULL,
	[msdyn_customvalue4] [nvarchar](max) NULL,
	[msdyn_documentname] [nvarchar](512) NULL,
	[msdyn_responsesashtmlrespondentlocale] [nvarchar](max) NULL,
	[msdyn_linkedanswer15name] [nvarchar](100) NULL,
	[msdyn_linkedanswer1name] [nvarchar](100) NULL,
	[msdyn_firstnameresponse] [nvarchar](max) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[msdyn_customvalue5] [nvarchar](max) NULL,
	[msdyn_linkedanswer6name] [nvarchar](100) NULL,
	[msdyn_postalcoderesponse] [nvarchar](max) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[msdyn_surveyresponseid] [uniqueidentifier] NULL,
	[msdyn_customnumber6] [decimal](38, 2) NULL,
	[msdyn_websiteresponse] [nvarchar](max) NULL,
	[msdyn_completedon] [datetime] NULL,
	[msdyn_customdate1] [datetime] NULL,
	[msdyn_customereffortscore] [decimal](38, 2) NULL,
	[msdyn_scoreaspercentageallroutes] [decimal](38, 4) NULL,
	[msdyn_linkedanswer14name] [nvarchar](100) NULL,
	[msdyn_accountyominame] [nvarchar](100) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[msdyn_referencenumber] [nvarchar](30) NULL,
	[msdyn_linkedanswer2name] [nvarchar](100) NULL,
	[importsequencenumber] [int] NULL,
	[versionnumber] [bigint] NULL,
	[msdyn_customvalue2] [nvarchar](max) NULL,
	[msdyn_jobtitleresponse] [nvarchar](max) NULL,
	[msdyn_telephoneresponse] [nvarchar](max) NULL,
	[msdyn_customnumber11] [decimal](38, 2) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[msdyn_username] [nvarchar](100) NULL,
	[msdyn_customnumber4] [decimal](38, 2) NULL,
	[msdyn_customnumber5] [decimal](38, 2) NULL,
	[msdyn_name] [nvarchar](100) NULL,
	[msdyn_customnumber7] [decimal](38, 2) NULL,
	[msdyn_customnumber1] [decimal](38, 2) NULL,
	[msdyn_customnumber2] [decimal](38, 2) NULL,
	[msdyn_customnumber3] [decimal](38, 2) NULL,
	[msdyn_customnumber12] [decimal](38, 2) NULL,
	[msdyn_emailrespondertrigger] [datetime] NULL,
	[msdyn_street3response] [nvarchar](max) NULL,
	[msdyn_customnumber8] [decimal](38, 2) NULL,
	[msdyn_customnumber9] [decimal](38, 2) NULL,
	[msdyn_linkedanswer7name] [nvarchar](100) NULL
)

-- phonecall
CREATE TABLE [dbo].[phonecall](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[directioncode] [bit] NULL,
	[leftvoicemail] [bit] NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[from] [uniqueidentifier] NULL,
	[to] [uniqueidentifier] NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[modifiedon] [datetime] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[scheduledstart] [datetime] NULL,
	[actualstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subcategory] [nvarchar](250) NULL,
	[subject] [nvarchar](200) NULL,
	[overriddencreatedon] [datetime] NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[phonenumber] [nvarchar](200) NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[scheduleddurationminutes] [int] NULL,
	[category] [nvarchar](250) NULL,
	[processid] [uniqueidentifier] NULL,
	[description] [nvarchar](max) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[sortdate] [datetime] NULL,
	[lastonholdtime] [datetime] NULL,
	[stageid] [uniqueidentifier] NULL,
	[scheduledend] [datetime] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[activityid] [uniqueidentifier] NULL,
	[onholdtime] [int] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[slaname] [nvarchar](100) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL
)

-- systemuser
CREATE TABLE [dbo].[systemuser](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[address1_addresstypecode] [int] NULL,
	[address1_shippingmethodcode] [int] NULL,
	[preferredemailcode] [int] NULL,
	[outgoingemaildeliverymethod] [int] NULL,
	[preferredphonecode] [int] NULL,
	[emailrouteraccessapproval] [int] NULL,
	[preferredaddresscode] [int] NULL,
	[incomingemaildeliverymethod] [int] NULL,
	[accessmode] [int] NULL,
	[caltype] [int] NULL,
	[address2_addresstypecode] [int] NULL,
	[invitestatuscode] [int] NULL,
	[address2_shippingmethodcode] [int] NULL,
	[setupuser] [bit] NULL,
	[islicensed] [bit] NULL,
	[isactivedirectoryuser] [bit] NULL,
	[displayinserviceviews] [bit] NULL,
	[defaultfilterspopulated] [bit] NULL,
	[isintegrationuser] [bit] NULL,
	[isemailaddressapprovedbyo365admin] [bit] NULL,
	[issyncwithdirectory] [bit] NULL,
	[isdisabled] [bit] NULL,
	[territoryid] [uniqueidentifier] NULL,
	[territoryid_entitytype] [nvarchar](128) NULL,
	[calendarid] [uniqueidentifier] NULL,
	[calendarid_entitytype] [nvarchar](128) NULL,
	[mobileofflineprofileid] [uniqueidentifier] NULL,
	[mobileofflineprofileid_entitytype] [nvarchar](128) NULL,
	[queueid] [uniqueidentifier] NULL,
	[queueid_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[defaultmailbox] [uniqueidentifier] NULL,
	[defaultmailbox_entitytype] [nvarchar](128) NULL,
	[positionid] [uniqueidentifier] NULL,
	[positionid_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[siteid] [uniqueidentifier] NULL,
	[siteid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[parentsystemuserid] [uniqueidentifier] NULL,
	[parentsystemuserid_entitytype] [nvarchar](128) NULL,
	[businessunitid] [uniqueidentifier] NULL,
	[businessunitid_entitytype] [nvarchar](128) NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[azureactivedirectoryobjectid] [uniqueidentifier] NULL,
	[address1_line1] [nvarchar](1024) NULL,
	[internalemailaddress] [nvarchar](100) NULL,
	[siteidname] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[address1_line3] [nvarchar](1024) NULL,
	[skills] [nvarchar](100) NULL,
	[yomifirstname] [nvarchar](64) NULL,
	[address1_longitude] [decimal](38, 5) NULL,
	[yomifullname] [nvarchar](200) NULL,
	[entityimage_timestamp] [bigint] NULL,
	[parentsystemuseridname] [nvarchar](100) NULL,
	[address2_county] [nvarchar](128) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[activedirectoryguid] [uniqueidentifier] NULL,
	[title] [nvarchar](128) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[passporthi] [int] NULL,
	[homephone] [nvarchar](50) NULL,
	[parentsystemuseridyominame] [nvarchar](100) NULL,
	[address2_stateorprovince] [nvarchar](128) NULL,
	[address2_country] [nvarchar](128) NULL,
	[address2_name] [nvarchar](100) NULL,
	[disabledreason] [nvarchar](500) NULL,
	[lastname] [nvarchar](64) NULL,
	[address1_city] [nvarchar](128) NULL,
	[address1_utcoffset] [int] NULL,
	[userlicensetype] [int] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[address2_city] [nvarchar](128) NULL,
	[passportlo] [int] NULL,
	[address2_latitude] [decimal](38, 5) NULL,
	[applicationid] [uniqueidentifier] NULL,
	[yomimiddlename] [nvarchar](50) NULL,
	[firstname] [nvarchar](64) NULL,
	[address2_postalcode] [nvarchar](40) NULL,
	[employeeid] [nvarchar](100) NULL,
	[processid] [uniqueidentifier] NULL,
	[mobileofflineprofileidname] [nvarchar](100) NULL,
	[governmentid] [nvarchar](100) NULL,
	[entityimage_url] [nvarchar](200) NULL,
	[address2_line3] [nvarchar](1024) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[address1_county] [nvarchar](128) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[address2_telephone2] [nvarchar](50) NULL,
	[address2_postofficebox] [nvarchar](40) NULL,
	[address2_telephone1] [nvarchar](50) NULL,
	[yomilastname] [nvarchar](64) NULL,
	[address2_telephone3] [nvarchar](50) NULL,
	[address1_addressid] [uniqueidentifier] NULL,
	[territoryidname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[systemuserid] [uniqueidentifier] NULL,
	[middlename] [nvarchar](50) NULL,
	[entityimageid] [uniqueidentifier] NULL,
	[address2_line2] [nvarchar](1024) NULL,
	[applicationiduri] [nvarchar](1024) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[mobilephone] [nvarchar](64) NULL,
	[address2_composite] [nvarchar](max) NULL,
	[address1_country] [nvarchar](128) NULL,
	[mobilealertemail] [nvarchar](100) NULL,
	[sharepointemailaddress] [nvarchar](1024) NULL,
	[businessunitidname] [nvarchar](100) NULL,
	[address1_stateorprovince] [nvarchar](128) NULL,
	[address2_utcoffset] [int] NULL,
	[jobtitle] [nvarchar](100) NULL,
	[nickname] [nvarchar](50) NULL,
	[address1_telephone1] [nvarchar](64) NULL,
	[address1_telephone2] [nvarchar](50) NULL,
	[address1_telephone3] [nvarchar](50) NULL,
	[address1_postofficebox] [nvarchar](40) NULL,
	[organizationid] [uniqueidentifier] NULL,
	[yammeremailaddress] [nvarchar](200) NULL,
	[defaultmailboxname] [nvarchar](100) NULL,
	[photourl] [nvarchar](200) NULL,
	[personalemailaddress] [nvarchar](100) NULL,
	[address2_longitude] [decimal](38, 5) NULL,
	[domainname] [nvarchar](1024) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[address2_fax] [nvarchar](50) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[address1_line2] [nvarchar](1024) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[address2_upszone] [nvarchar](4) NULL,
	[windowsliveid] [nvarchar](1024) NULL,
	[salutation] [nvarchar](20) NULL,
	[address1_postalcode] [nvarchar](40) NULL,
	[stageid] [uniqueidentifier] NULL,
	[defaultodbfoldername] [nvarchar](200) NULL,
	[address1_composite] [nvarchar](max) NULL,
	[positionidname] [nvarchar](100) NULL,
	[address2_addressid] [uniqueidentifier] NULL,
	[yammeruserid] [nvarchar](128) NULL,
	[importsequencenumber] [int] NULL,
	[organizationidname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[queueidname] [nvarchar](400) NULL,
	[address1_name] [nvarchar](100) NULL,
	[address1_fax] [nvarchar](64) NULL,
	[address1_latitude] [decimal](38, 5) NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[address2_line1] [nvarchar](1024) NULL,
	[address1_upszone] [nvarchar](4) NULL,
	[fullname] [nvarchar](200) NULL
)



--skakpiinstance
CREATE TABLE [dbo].[slakpiinstance](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[status] [int] NULL,
	[warningtimereached] [int] NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[regarding] [uniqueidentifier] NULL,
	[regarding_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[description] [nvarchar](100) NULL,
	[regardingyominame] [nvarchar](400) NULL,
	[name] [nvarchar](100) NULL,
	[regardingobjecttypecode] [nvarchar](4000) NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[computedwarningtime] [datetime] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[computedfailuretime] [datetime] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[slakpiinstanceid] [uniqueidentifier] NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[warningtime] [datetime] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[modifiedon] [datetime] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[createdon] [datetime] NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[regardingidname] [nvarchar](100) NULL,
	[failuretime] [datetime] NULL,
	[regardingname] [nvarchar](100) NULL,
	[versionnumber] [bigint] NULL,
	[succeededon] [datetime] NULL
)

GO

-- task
CREATE TABLE [dbo].[task](
	[Id] [uniqueidentifier] NOT NULL,
	[SinkCreatedOn] [datetime] NULL,
	[SinkModifiedOn] [datetime] NULL,
	[statecode] [int] NULL,
	[statuscode] [int] NULL,
	[prioritycode] [int] NULL,
	[isbilled] [bit] NULL,
	[isworkflowcreated] [bit] NULL,
	[isregularactivity] [bit] NULL,
	[createdonbehalfby] [uniqueidentifier] NULL,
	[createdonbehalfby_entitytype] [nvarchar](128) NULL,
	[modifiedonbehalfby] [uniqueidentifier] NULL,
	[modifiedonbehalfby_entitytype] [nvarchar](128) NULL,
	[regardingobjectid] [uniqueidentifier] NULL,
	[regardingobjectid_entitytype] [nvarchar](128) NULL,
	[slaid] [uniqueidentifier] NULL,
	[slaid_entitytype] [nvarchar](128) NULL,
	[owningteam] [uniqueidentifier] NULL,
	[owningteam_entitytype] [nvarchar](128) NULL,
	[transactioncurrencyid] [uniqueidentifier] NULL,
	[transactioncurrencyid_entitytype] [nvarchar](128) NULL,
	[slainvokedid] [uniqueidentifier] NULL,
	[slainvokedid_entitytype] [nvarchar](128) NULL,
	[createdby] [uniqueidentifier] NULL,
	[createdby_entitytype] [nvarchar](128) NULL,
	[modifiedby] [uniqueidentifier] NULL,
	[modifiedby_entitytype] [nvarchar](128) NULL,
	[serviceid] [uniqueidentifier] NULL,
	[serviceid_entitytype] [nvarchar](128) NULL,
	[owninguser] [uniqueidentifier] NULL,
	[owninguser_entitytype] [nvarchar](128) NULL,
	[owningbusinessunit] [uniqueidentifier] NULL,
	[owningbusinessunit_entitytype] [nvarchar](128) NULL,
	[ownerid] [uniqueidentifier] NULL,
	[ownerid_entitytype] [nvarchar](128) NULL,
	[versionnumber] [bigint] NULL,
	[createdon] [datetime] NULL,
	[traversedpath] [nvarchar](1250) NULL,
	[modifiedbyyominame] [nvarchar](100) NULL,
	[owneridtype] [nvarchar](4000) NULL,
	[crmtaskassigneduniqueid] [uniqueidentifier] NULL,
	[modifiedbyname] [nvarchar](100) NULL,
	[onholdtime] [int] NULL,
	[regardingobjectidyominame] [nvarchar](100) NULL,
	[owneridname] [nvarchar](100) NULL,
	[overriddencreatedon] [datetime] NULL,
	[scheduledstart] [datetime] NULL,
	[actualstart] [datetime] NULL,
	[createdonbehalfbyyominame] [nvarchar](100) NULL,
	[subscriptionid] [uniqueidentifier] NULL,
	[exchangerate] [decimal](38, 10) NULL,
	[subcategory] [nvarchar](250) NULL,
	[timezoneruleversionnumber] [int] NULL,
	[regardingobjectidname] [nvarchar](100) NULL,
	[activityadditionalparams] [nvarchar](max) NULL,
	[createdonbehalfbyname] [nvarchar](100) NULL,
	[activitytypecode] [nvarchar](4000) NULL,
	[utcconversiontimezonecode] [int] NULL,
	[importsequencenumber] [int] NULL,
	[owneridyominame] [nvarchar](100) NULL,
	[scheduleddurationminutes] [int] NULL,
	[category] [nvarchar](250) NULL,
	[processid] [uniqueidentifier] NULL,
	[description] [nvarchar](max) NULL,
	[slaname] [nvarchar](100) NULL,
	[createdbyname] [nvarchar](100) NULL,
	[sortdate] [datetime] NULL,
	[lastonholdtime] [datetime] NULL,
	[stageid] [uniqueidentifier] NULL,
	[modifiedon] [datetime] NULL,
	[percentcomplete] [int] NULL,
	[createdbyyominame] [nvarchar](100) NULL,
	[transactioncurrencyidname] [nvarchar](100) NULL,
	[actualend] [datetime] NULL,
	[activityid] [uniqueidentifier] NULL,
	[modifiedonbehalfbyname] [nvarchar](100) NULL,
	[slainvokedidname] [nvarchar](100) NULL,
	[scheduledend] [datetime] NULL,
	[modifiedonbehalfbyyominame] [nvarchar](100) NULL,
	[actualdurationminutes] [int] NULL,
	[subject] [nvarchar](200) NULL
)


-- Team
CREATE TABLE dbo.team
(
	id                               UNIQUEIDENTIFIER NOT NULL,
	sinkcreatedon                    DATETIME NULL,
	sinkmodifiedon                   DATETIME NULL,
	teamtype                         INT NULL,
	systemmanaged                    BIT NULL,
	isdefault                        BIT NULL,
	modifiedonbehalfby               UNIQUEIDENTIFIER NULL,
	modifiedonbehalfby_entitytype    NVARCHAR(128) NULL,
	administratorid                  UNIQUEIDENTIFIER NULL,
	administratorid_entitytype       NVARCHAR(128) NULL,
	createdonbehalfby                UNIQUEIDENTIFIER NULL,
	createdonbehalfby_entitytype     NVARCHAR(128) NULL,
	transactioncurrencyid            UNIQUEIDENTIFIER NULL,
	transactioncurrencyid_entitytype NVARCHAR(128) NULL,
	regardingobjectid                UNIQUEIDENTIFIER NULL,
	regardingobjectid_entitytype     NVARCHAR(128) NULL,
	businessunitid                   UNIQUEIDENTIFIER NULL,
	businessunitid_entitytype        NVARCHAR(128) NULL,
	modifiedby                       UNIQUEIDENTIFIER NULL,
	modifiedby_entitytype            NVARCHAR(128) NULL,
	createdby                        UNIQUEIDENTIFIER NULL,
	createdby_entitytype             NVARCHAR(128) NULL,
	teamtemplateid                   UNIQUEIDENTIFIER NULL,
	teamtemplateid_entitytype        NVARCHAR(128) NULL,
	queueid                          UNIQUEIDENTIFIER NULL,
	queueid_entitytype               NVARCHAR(128) NULL,
	traversedpath                    NVARCHAR(1250) NULL,
	transactioncurrencyidname        NVARCHAR(100) NULL,
	[description]                    NVARCHAR(max) NULL,
	queueidname                      NVARCHAR(400) NULL,
	modifiedbyyominame               NVARCHAR(100) NULL,
	teamid                           UNIQUEIDENTIFIER NULL,
	name                             NVARCHAR(160) NULL,
	stageid                          UNIQUEIDENTIFIER NULL,
	regardingobjecttypecode          NVARCHAR(max) NULL,
	importsequencenumber             INT NULL,
	organizationid                   UNIQUEIDENTIFIER NULL,
	businessunitidname               NVARCHAR(100) NULL,
	emailaddress                     NVARCHAR(100) NULL,
	createdbyyominame                NVARCHAR(100) NULL,
	modifiedbyname                   NVARCHAR(100) NULL,
	versionnumber                    BIGINT NULL,
	administratoridname              NVARCHAR(100) NULL,
	administratoridyominame          NVARCHAR(100) NULL,
	exchangerate                     DECIMAL(38, 10) NULL,
	createdonbehalfbyyominame        NVARCHAR(100) NULL,
	processid                        UNIQUEIDENTIFIER NULL,
	yominame                         NVARCHAR(160) NULL,
	modifiedon                       DATETIME NULL,
	modifiedonbehalfbyyominame       NVARCHAR(100) NULL,
	createdbyname                    NVARCHAR(100) NULL,
	createdon                        DATETIME NULL,
	organizationidname               NVARCHAR(100) NULL,
	modifiedonbehalfbyname           NVARCHAR(100) NULL,
	createdonbehalfbyname            NVARCHAR(100) NULL,
	overriddencreatedon              DATETIME NULL
);

/* CSRV specific schemas */

CREATE TABLE csrv.[configuration]
(
  id                     INT IDENTITY(1, 1) NOT NULL,
  configuration_group    VARCHAR(150) NOT NULL,
  configuration_subgroup VARCHAR(150) NOT NULL,
  name                   VARCHAR(150) NOT NULL,
  value                  VARCHAR(max) NULL,
  visible                BIT NOT NULL DEFAULT 0
);

CREATE TABLE [csrv].[entityinitialcount](
	[entityname] [nvarchar](40) NULL,
	[initialcount] INT NULL,
	[lastcount] INT NULL,
	[lasttimestamp] DATETIME2 NULL
);


CREATE TABLE csrv.[date]
(
   date_key               INT NOT NULL,
   full_date              DATE NOT NULL,
   day_of_week            TINYINT NOT NULL,
   day_num_in_month       TINYINT NOT NULL,
   day_name               NVARCHAR(50) NOT NULL,
   day_abbrev             NVARCHAR(10) NOT NULL,
   weekday_flag           CHAR(1) NOT NULL,
   week_num_in_year       TINYINT NOT NULL,
   week_begin_date        DATE NOT NULL,
   [month]                TINYINT NOT NULL,
   month_name             NVARCHAR(50) NOT NULL,
   month_abbrev           NVARCHAR(10) NOT NULL,
   [quarter]              TINYINT NOT NULL,
   [year]                 SMALLINT NOT NULL,
   yearmo                 INT NOT NULL,
   same_day_year_ago_date DATE NOT NULL
   CONSTRAINT pk_dim_date PRIMARY KEY CLUSTERED (date_key)
);

