SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='batch_log' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.[batch_log];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='user' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.[user];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='20_PowerBI' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.[20_PowerBI];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='staging_20_PowerBI' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.[staging_20_PowerBI];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='adtlog' AND TABLE_NAME='trace_log' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE adtlog.[trace_log];

-- Stored Procedures
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='adtlog' AND ROUTINE_NAME='uspMoveStaging' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE adtlog.uspMoveStaging;

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='adtlog')
BEGIN
    EXEC ('CREATE SCHEMA adtlog AUTHORIZATION dbo');
END;
